In [ ]:
import pandas as pd             # For handling data (DataFrame)
import seaborn as sns           # For visualizations and Planets dataset
import numpy as np              # For numerical operations
# import matplotlib.pyplot as plt # For plots
# import math

# from pandas import plotting

# import statsmodels.formula.api as smf
# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
Drivers_df = pd.read_csv("https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/main/final/Drivers_abridge.csv", usecols = lambda x: x not in ["Latitude", "Longitude", "Person_ID"])
Drivers_df.head()

,Report_Number,Agency_Name,ACRS_Report_Type,Crash_Date_Time,Route_Type,Road_Name,Cross_Street,Off_Road_Descript,Related_Non_Motorist,Collision_Type,...,Veh_1st_Impact_Loc,Veh_Body_Type,Vehicle_Movement,Veh_Going_Dir,Speed_Limit,Driverless_Vehicle,Parked_Vehicle,Vehicle_Year,Vehicle_Make,Veh_Model
0,MCP293200B1,MONTGOMERY,Injury Crash,5/5/26 22:43,Maryland (State) Route,NEW HAMPSHIRE AVE (SB/L),NaN,NaN,NaN,Front to Front,...,One O Clock,Passenger Car,Moving Constant Speed,Southbound,40,No,No,2018,VOLKSWAGEN,GOLF GTI
1,MCP293200B1,MONTGOMERY,Injury Crash,5/5/26 22:43,Maryland (State) Route,NEW HAMPSHIRE AVE (SB/L),NaN,NaN,NaN,Front to Front,...,One O Clock,Passenger Car,Moving Constant Speed,Northbound,40,No,No,2026,HONDA,CIVIC
2,DD5631006M,ROCKVILLE,Property Damage Crash,5/5/26 21:43,Maryland (State) Route,VEIRS MILL RD,NaN,NaN,NaN,Front to Rear,...,Six O Clock,Passenger Car,Stopped in Traffic,Eastbound,35,No,No,2023,TOYOTA,RAV4
3,DD5631006M,ROCKVILLE,Property Damage Crash,5/5/26 21:43,Maryland (State) Route,VEIRS MILL RD,NaN,NaN,NaN,Front to Rear,...,Twelve O Clock,Passenger Car,Accelerating,Eastbound,35,No,No,2005,TOYOTA,CAMRY
4,MCP2737006P,MONTGOMERY,Property Damage Crash,5/5/26 21:30,County Route,PIPING ROCK DR,NEW HAMPSHIRE AVE,NaN,NaN,Angle,...,One O Clock,Sport Utility Vehicle,Entering Traffic Lane,Westbound,25,No,No,2025,KIA,SORENTO

In [ ]:
# Upload Raw file from GitHub

# Skip column because many contain 2 values instead of 1
Incidents_df = pd.read_csv("https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/main/final/Incidents_abridge.csv", usecols = lambda x: x not in ["Num_of_Lanes"])
Incidents_df.head()

,Report_Number,Hit_Run,Lane_Direction,Lane_Type,Road_Grade,At Fault,First_Harmful_Event,Second_Harmful_Event,Junction,Intersection_Type,Road Alignment,Road_Condition,Road_Division,Latitude,Longitude,Location
0,MCP293200B1,No,Southbound,Lane 2,Level,DRIVER,Motor Vehicle In Transport,NaN,Non-Junction,NaN,Straight,No Defects,"Divided, Raised Median (curbed)",39.032711,-76.985394,"(39.03271067, -76.98539433)"
1,DD5631006M,No,Eastbound,Lane 2,Downhill,UNKNOWN,Motor Vehicle In Transport,Motor Vehicle In Transport,Acceleration/Deceleration Lane,NaN,Straight,No Defects,"Divided, Raised Median (curbed)",39.078660,-77.132051,"(39.07866033, -77.13205117)"
2,MCP2737006P,No,"Northbound, Westbound",Lane 1,Level,DRIVER,Motor Vehicle In Transport,Not Applicable,Crossover-Related,NaN,Straight,No Defects,"Divided, Raised Median (curbed)",39.096986,-77.002564,"(39.09698583, -77.00256383)"
3,MCP3386004J,Yes,Westbound,Unknown,Level,UNKNOWN,Pedalcycle,NaN,Non-Junction,NaN,Straight,Unknown,"Divided, Raised Median (curbed)",38.998174,-77.109564,"(38.99817407, -77.10956426)"
4,MCP3232007N,No,"Northbound, Westbound",Lane 1,Level,DRIVER,Motor Vehicle In Transport,NaN,Intersection or Related,Perpendicular,Straight,No Defects,Not Divided,39.146563,-77.050454,"(39.14656267, -77.05045383)"

In [ ]:

Drivers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214273 entries, 0 to 214272
Data columns (total 33 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Report_Number               214273 non-null  object
 1   Agency_Name                 214273 non-null  object
 2   ACRS_Report_Type            214273 non-null  object
 3   Crash_Date_Time             214273 non-null  object
 4   Route_Type                  193237 non-null  object
 5   Road_Name                   189144 non-null  object
 6   Cross_Street                171506 non-null  object
 7   Off_Road_Descript           19994 non-null   object
 8   Related_Non_Motorist        7023 non-null    object
 9   Collision_Type              213688 non-null  object
 10  Weather                     200917 non-null  object
 11  Surface_Condition           189880 non-null  object
 12  Ambient_Light               212828 non-null  object
 13  Traffic_Control             184788 non-null  object
 14  Driver_Substance_Use        182953 non-null  object
 15  Non_Motorist_Substance_Use  5877 non-null    object
 16  Driver_At_Fault             214273 non-null  object
 17  Injury_Severity             211299 non-null  object
 18  Circumstance                41805 non-null   object
 19  Driver_Distraction          211096 non-null  object
 20  Drivers_License_State       199506 non-null  object
 21  Vehicle_ID                  214273 non-null  object
 22  Vehicle_Damage              213957 non-null  object
 23  Veh_1st_Impact_Loc          214117 non-null  object
 24  Veh_Body_Type               210998 non-null  object
 25  Vehicle_Movement            212487 non-null  object
 26  Veh_Going_Dir               204064 non-null  object
 27  Speed_Limit                 214273 non-null  int64
 28  Driverless_Vehicle          214273 non-null  object
 29  Parked_Vehicle              212747 non-null  object
 30  Vehicle_Year                214273 non-null  int64
 31  Vehicle_Make                213031 non-null  object
 32  Veh_Model                   212989 non-null  object
dtypes: int64(2), object(31)
memory usage: 53.9+ MB

In [ ]:
Incidents_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121640 entries, 0 to 121639
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Report_Number         121640 non-null  object
 1   Hit_Run               117023 non-null  object
 2   Lane_Direction        106118 non-null  object
 3   Lane_Type             30571 non-null   object
 4   Road_Grade            105553 non-null  object
 5   At Fault              121640 non-null  object
 6   First_Harmful_Event   120990 non-null  object
 7   Second_Harmful_Event  30512 non-null   object
 8   Junction              91843 non-null   object
 9   Intersection_Type     54940 non-null   object
 10  Road Alignment        105771 non-null  object
 11  Road_Condition        100871 non-null  object
 12  Road_Division         104991 non-null  object
 13  Latitude              121640 non-null  float64
 14  Longitude             121640 non-null  float64
 15  Location              121640 non-null  object
dtypes: float64(2), object(14)
memory usage: 14.8+ MB

In [ ]:
# Use left merge to keep all rows of Drivers_df, discard rows from Incidents_df
#that don't have a match in the key (Report_Number) column

merged_df = pd.merge(
    Drivers_df, Incidents_df, how = "left", on = ["Report_Number"]
)
#merged_df.head()

In [ ]:
#merged_df.info()

In [ ]:
merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].apply(lambda x: np.where(x < 1930, np.nan, x))

In [ ]:
merged_df[merged_df["Vehicle_Year"] < 1930].count() # check if it worked

Report_Number                 0
Agency_Name                   0
ACRS_Report_Type              0
Crash_Date_Time               0
Route_Type                    0
Road_Name                     0
Cross_Street                  0
Off_Road_Descript             0
Related_Non_Motorist          0
Collision_Type                0
Weather                       0
Surface_Condition             0
Ambient_Light                 0
Traffic_Control               0
Driver_Substance_Use          0
Non_Motorist_Substance_Use    0
Driver_At_Fault               0
Injury_Severity               0
Circumstance                  0
Driver_Distraction            0
Drivers_License_State         0
Vehicle_ID                    0
Vehicle_Damage                0
Veh_1st_Impact_Loc            0
Veh_Body_Type                 0
Vehicle_Movement              0
Veh_Going_Dir                 0
Speed_Limit                   0
Driverless_Vehicle            0
Parked_Vehicle                0
Vehicle_Year                  0
Vehicle_Make                  0
Veh_Model                     0
Hit_Run                       0
Lane_Direction                0
Lane_Type                     0
Road_Grade                    0
At Fault                      0
First_Harmful_Event           0
Second_Harmful_Event          0
Junction                      0
Intersection_Type             0
Road Alignment                0
Road_Condition                0
Road_Division                 0
Latitude                      0
Longitude                     0
Location                      0
dtype: int64

In [ ]:
merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].apply(lambda x: np.where(x > 2026, np.nan, x))
merged_df[merged_df["Vehicle_Year"] > 2026].count()

Report_Number                 0
Agency_Name                   0
ACRS_Report_Type              0
Crash_Date_Time               0
Route_Type                    0
Road_Name                     0
Cross_Street                  0
Off_Road_Descript             0
Related_Non_Motorist          0
Collision_Type                0
Weather                       0
Surface_Condition             0
Ambient_Light                 0
Traffic_Control               0
Driver_Substance_Use          0
Non_Motorist_Substance_Use    0
Driver_At_Fault               0
Injury_Severity               0
Circumstance                  0
Driver_Distraction            0
Drivers_License_State         0
Vehicle_ID                    0
Vehicle_Damage                0
Veh_1st_Impact_Loc            0
Veh_Body_Type                 0
Vehicle_Movement              0
Veh_Going_Dir                 0
Speed_Limit                   0
Driverless_Vehicle            0
Parked_Vehicle                0
Vehicle_Year                  0
Vehicle_Make                  0
Veh_Model                     0
Hit_Run                       0
Lane_Direction                0
Lane_Type                     0
Road_Grade                    0
At Fault                      0
First_Harmful_Event           0
Second_Harmful_Event          0
Junction                      0
Intersection_Type             0
Road Alignment                0
Road_Condition                0
Road_Division                 0
Latitude                      0
Longitude                     0
Location                      0
dtype: int64

In [ ]:
merged_df.describe()

         Speed_Limit   Vehicle_Year       Latitude      Longitude
count  214273.000000  208779.000000  214273.000000  214273.000000
mean       32.083720    2011.551152      39.082996     -77.111936
std        11.385475       6.662198       0.071774       0.097885
min         0.000000    1930.000000      37.720000     -79.486000
25%        25.000000    2007.000000      39.024517     -77.189153
50%        35.000000    2013.000000      39.074771     -77.104985
75%        40.000000    2016.000000      39.139512     -77.039154
max        75.000000    2026.000000      39.990414     -75.527708

In [ ]:
merged_df.nunique()

Report_Number                 120880
Agency_Name                       10
ACRS_Report_Type                   3
Crash_Date_Time               117933
Route_Type                        19
Road_Name                       4837
Cross_Street                    7569
Off_Road_Descript              14276
Related_Non_Motorist              28
Collision_Type                    28
Weather                           23
Surface_Condition                 21
Ambient_Light                     16
Traffic_Control                   34
Driver_Substance_Use              20
Non_Motorist_Substance_Use        27
Driver_At_Fault                    3
Injury_Severity                   10
Circumstance                     854
Driver_Distraction                24
Drivers_License_State             81
Vehicle_ID                    214273
Vehicle_Damage                    12
Veh_1st_Impact_Loc                33
Veh_Body_Type                     60
Vehicle_Movement                  36
Veh_Going_Dir                     10
Speed_Limit                       16
Driverless_Vehicle                 2
Parked_Vehicle                     2
Vehicle_Year                      72
Vehicle_Make                    1965
Veh_Model                       7193
Hit_Run                            2
Lane_Direction                    39
Lane_Type                        214
Road_Grade                        24
At Fault                           4
First_Harmful_Event               67
Second_Harmful_Event              64
Junction                          22
Intersection_Type                 11
Road Alignment                    12
Road_Condition                    21
Road_Division                     36
Latitude                      108078
Longitude                     110275
Location                      120115
dtype: int64

In [ ]:
unique_agency_name = merged_df["Agency_Name"].unique()
print(unique_agency_name)

['MONTGOMERY' 'ROCKVILLE' 'TAKOMA' 'GAITHERSBURG' 'MCPARK'
 'Montgomery County Police' 'Rockville Police Departme'
 'Gaithersburg Police Depar' 'Maryland-National Capital'
 'Takoma Park Police Depart']

In [ ]:
print(merged_df["ACRS_Report_Type"].unique())

['Injury Crash' 'Property Damage Crash' 'Fatal Crash']

In [ ]:
column_list = merged_df.columns.tolist()
print(column_list)

['Report_Number', 'Agency_Name', 'ACRS_Report_Type', 'Crash_Date_Time', 'Route_Type', 'Road_Name', 'Cross_Street', 'Off_Road_Descript', 'Related_Non_Motorist', 'Collision_Type', 'Weather', 'Surface_Condition', 'Ambient_Light', 'Traffic_Control', 'Driver_Substance_Use', 'Non_Motorist_Substance_Use', 'Driver_At_Fault', 'Injury_Severity', 'Circumstance', 'Driver_Distraction', 'Drivers_License_State', 'Vehicle_ID', 'Vehicle_Damage', 'Veh_1st_Impact_Loc', 'Veh_Body_Type', 'Vehicle_Movement', 'Veh_Going_Dir', 'Speed_Limit', 'Driverless_Vehicle', 'Parked_Vehicle', 'Vehicle_Year', 'Vehicle_Make', 'Veh_Model', 'Hit_Run', 'Lane_Direction', 'Lane_Type', 'Road_Grade', 'At Fault', 'First_Harmful_Event', 'Second_Harmful_Event', 'Junction', 'Intersection_Type', 'Road Alignment', 'Road_Condition', 'Road_Division', 'Latitude', 'Longitude', 'Location']

In [ ]:
# run only once
for i in column_list:
  print(f"{i} : \n{merged_df[i].unique()}\n\n")

Report_Number :
['MCP293200B1' 'DD5631006M' 'MCP2737006P' ... 'MCP2783000G' 'MCP2686000D'
 'MCP11520005']


Agency_Name :
['MONTGOMERY' 'ROCKVILLE' 'TAKOMA' 'GAITHERSBURG' 'MCPARK'
 'Montgomery County Police' 'Rockville Police Departme'
 'Gaithersburg Police Depar' 'Maryland-National Capital'
 'Takoma Park Police Depart']


ACRS_Report_Type :
['Injury Crash' 'Property Damage Crash' 'Fatal Crash']


Crash_Date_Time :
['5/5/26 22:43' '5/5/26 21:43' '5/5/26 21:30' ... '1/1/15 1:14'
 '1/1/15 1:10' '1/1/15 0:30']


Route_Type :
['Maryland (State) Route' 'County Route' 'Spur' nan 'US (State)'
 'Local Route' 'Municipality Route' 'Other Public Roadway' 'Bicycle Route'
 'Ramp' 'Crossover' 'Interstate (State)' 'Private Route'
 'Government Route' 'Service Road' 'County' 'Maryland (State)'
 'Municipality' 'Government' 'Unknown']


Road_Name :
['NEW HAMPSHIRE AVE (SB/L)' 'VEIRS MILL RD' 'PIPING ROCK DR' ...
 'BURTON PARRISH WAY' 'BRUTON PARRISH WAY' 'LAVEROCK CT']


Cross_Street :
[nan 'NEW HAMPSHIRE AVE' 'OLNEY SANDY SPRING RD (WB/L)' ... 'SQUIRES CT'
 'WATER ST (AHEAD)' 'BETTSWOOD DR']


Off_Road_Descript :
[nan 'Parking Stall     '
 'Parking Lot Way        PARKING LOT OF 10109 COLESVILLE ROAD' ...
 '11241 LOCKWOOD DRIVE' 'Parking Lot of 14939 Shady Grove Rd'
 'Parking lot at 4841 Bethesda Ave']


Related_Non_Motorist :
[nan 'Cyclist (non-electric)' 'Pedestrian' 'Cyclist (Electric)'
 'Occupant Of a Non-Motor Vehicle Transportation Device'
 'Scooter (non-Electric)' 'Scooter (electric)' 'Unknown'
 'Other Pedestrian (person in a building, skater, personal conveyance, etc.)'
 'Wheelchair (electric)' 'Unknown Type Of Non-Motorist'
 'Occupant of Motor Vehicle Not in Transport'
 'Occupant of Motor Vehicle Not in Transport, Pedestrian'
 'Pedestrian, Wheelchair (non-electric)' 'Unknown, Wheelchair (electric)'
 'Wheelchair (non-electric)'
 'Other Pedestrian (person in a building, skater, personal conveyance, etc.), Pedestrian'
 'PEDESTRIAN' 'OTHER' 'BICYCLIST' 'MACHINE OPERATOR/RIDER'
 'OTHER PEDALCYCLIST' 'OTHER, PEDESTRIAN' 'OTHER CONVEYANCE'
 'OTHER CONVEYANCE, PEDESTRIAN' 'BICYCLIST, OTHER' 'BICYCLIST, PEDESTRIAN'
 'IN ANIMAL-DRAWN VEH' 'OTHER, OTHER CONVEYANCE']


Collision_Type :
['Front to Front' 'Front to Rear' 'Angle' 'Single Vehicle'
 'Sideswipe, Opposite Direction' 'Other' 'Rear To Side' 'Rear To Rear'
 'Sideswipe, Same Direction' 'Unknown' 'OPPOSITE DIRECTION SIDESWIPE'
 'SINGLE VEHICLE' 'HEAD ON LEFT TURN' 'STRAIGHT MOVEMENT ANGLE' 'OTHER'
 'SAME DIR REAR END' 'HEAD ON' 'SAME DIRECTION SIDESWIPE' nan
 'SAME DIRECTION RIGHT TURN' 'SAME DIRECTION LEFT TURN'
 'ANGLE MEETS LEFT TURN' 'SAME DIR BOTH LEFT TURN'
 'SAME DIR REND LEFT TURN' 'UNKNOWN' 'ANGLE MEETS RIGHT TURN'
 'OPPOSITE DIR BOTH LEFT TURN' 'ANGLE MEETS LEFT HEAD ON'
 'SAME DIR REND RIGHT TURN']


Weather :
['Clear' 'Rain' 'Cloudy' 'Unknown' 'Fog, Smog, Smoke'
 'Freezing Rain Or Freezing Drizzle' 'Sleet Or Hail' 'Snow' 'Blowing Snow'
 'Severe Crosswinds' 'Blowing Sand, Soil, Dirt' 'CLOUDY' 'CLEAR' nan
 'UNKNOWN' 'RAINING' 'FOGGY' 'OTHER' 'SLEET' 'WINTRY MIX' 'SNOW'
 'SEVERE WINDS' 'BLOWING SNOW' 'BLOWING SAND, SOIL, DIRT']


Surface_Condition :
['Dry' nan 'Wet' 'Other' 'Water (standing, moving)' 'Ice/Frost' 'Slush'
 'Snow' 'Mud, Dirt, Gravel' 'Oil' 'Sand' 'DRY' 'WET' 'ICE'
 'WATER(STANDING/MOVING)' 'UNKNOWN' 'SNOW' 'SLUSH' 'OTHER'
 'MUD, DIRT, GRAVEL' 'OIL' 'SAND']


Ambient_Light :
['Dark - Lighted' 'Dark - Unknown Lighting' 'Daylight'
 'Dark - Not Lighted' 'Dusk' 'Dawn' 'Unknown' 'Other' 'DAYLIGHT'
 'DARK NO LIGHTS' 'DARK LIGHTS ON' 'DAWN' 'DARK -- UNKNOWN LIGHTING'
 'DUSK' 'OTHER' nan 'UNKNOWN']


Traffic_Control :
['No Controls' 'Flashing Traffic Control Signal' 'Lane Use Control Signal'
 'Traffic Control Signal' nan 'Intersection Ahead Warning Sign'
 'Stop Sign'
 'Other Pavement Marking (excluding edgelines, centerlines, or lane lines)'
 'Other Signal' 'Other' 'Pedestrian Crossing Sign' 'Yield Sign'
 'School Zone Sign' 'Other Warning Sign' 'Pedestrian Crossing'
 'Person (including flagger, law enforcement, crossing guard, etc.'
 'Flashing Railroad Crossing Signal (may include gates)'
 'Flashing School Zone Signal' 'Ramp Meter Signal'
 'Reduce Speed Ahead Warning Sign' 'Bicycle Crossing Sign'
 'Curve Ahead Warning Sign' 'Railroad Crossing' 'School Zone'
 'NO CONTROLS' 'TRAFFIC SIGNAL' 'YIELD SIGN' 'RAILWAY CROSSING DEVICE'
 'STOP SIGN' 'FLASHING TRAFFIC SIGNAL' 'PERSON' 'OTHER' 'UNKNOWN'
 'WARNING SIGN' 'SCHOOL ZONE SIGN DEVICE']


Driver_Substance_Use :
['Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Suspect of Alcohol Use, Not Suspect of Drug Use' 'Unknown, Unknown'
 'Suspect of Alcohol Use, Unknown'
 'Not Suspect of Alcohol Use, Suspect of Drug Use'
 'Suspect of Alcohol Use, Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Unknown' 'Unknown, Not Suspect of Drug Use'
 'Unknown, Suspect of Drug Use' 'NONE DETECTED' 'UNKNOWN' nan
 'ALCOHOL PRESENT' 'ALCOHOL CONTRIBUTED' 'ILLEGAL DRUG PRESENT'
 'MEDICATION CONTRIBUTED' 'COMBINATION CONTRIBUTED'
 'ILLEGAL DRUG CONTRIBUTED' 'COMBINED SUBSTANCE PRESENT'
 'MEDICATION PRESENT' 'OTHER']


Non_Motorist_Substance_Use :
[nan 'Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Unknown, Unknown' 'Not Suspect of Alcohol Use, Suspect of Drug Use'
 'Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Unknown' 'Suspect of Alcohol Use, Unknown'
 'Unknown, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Suspect of Alcohol Use, Suspect of Drug Use'
 'Unknown, Suspect of Drug Use'
 'Unknown, Unknown, Unknown, Not Suspect of Drug Use' 'NONE DETECTED'
 'ALCOHOL PRESENT' 'UNKNOWN' 'ALCOHOL CONTRIBUTED'
 'ALCOHOL CONTRIBUTED, ALCOHOL PRESENT' 'N/A, NONE DETECTED'
 'ILLEGAL DRUG PRESENT' 'ILLEGAL DRUG CONTRIBUTED' 'N/A, UNKNOWN'
 'MEDICATION PRESENT' 'COMBINATION CONTRIBUTED' 'NONE DETECTED, UNKNOWN'
 'COMBINED SUBSTANCE PRESENT' 'ALCOHOL PRESENT, NONE DETECTED' 'OTHER']


Driver_At_Fault :
['No' 'Yes' 'Unknown']


Injury_Severity :
['Suspected Minor Injury' 'No Apparent Injury' nan 'Possible Injury'
 'Suspected Serious Injury' 'Fatal Injury' 'NO APPARENT INJURY'
 'SUSPECTED MINOR INJURY' 'POSSIBLE INJURY' 'SUSPECTED SERIOUS INJURY'
 'FATAL INJURY']


Circumstance :
[nan
 'Disregarded Other Road Markings, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Wrong Side, Wrong Way'
 'Other Improper Action'
 'Followed Too Closely, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action'
 'Failed to Yield Right-of-Way' 'Ran Red Light'
 'Other Improper Action, Swerved or Avoided Due to Wind, Slippery Surface, Motor Vehicle, Object, Non-Motorist in Roadway, etc'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner'
 'Followed Too Closely, Swerved or Avoided Due to Wind, Slippery Surface, Motor Vehicle, Object, Non-Motorist in Roadway, etc'
 'Followed Too Closely, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Too Fast For Conditions'
 'Followed Too Closely' 'Improper Passing'
 'Failed to Keep in Proper Lane, Ran Off Roadway, Swerved or Avoided Due to Wind, Slippery Surface, Motor Vehicle, Object, Non-Motorist in Roadway, etc'
 'Disregarded Other Road Markings, Failed to Keep in Proper Lane, Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action'
 'Improper Backing'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Swerved or Avoided Due to Wind, Slippery Surface, Motor Vehicle, Object, Non-Motorist in Roadway, etc'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner'
 'Followed Too Closely, Too Fast For Conditions'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner'
 'Failed to Yield Right-of-Way, Other Improper Action, Ran Red Light'
 'Disregarded Other Road Markings, Failed to Keep in Proper Lane, Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Ran Off Roadway'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner'
 'Swerved or Avoided Due to Wind, Slippery Surface, Motor Vehicle, Object, Non-Motorist in Roadway, etc'
 'Over-Correcting/Over-Steering' 'Failed to Keep in Proper Lane'
 'Disregarded Other Road Markings, Disregarded Other Traffic Sign, Ran Off Roadway'
 'Failed to Keep in Proper Lane, Failed to Yield Right-of-Way, Other Improper Action'
 'Improper Turn, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action'
 'Followed Too Closely, Other Improper Action' 'Ran Off Roadway'
 'Improper Turn' 'Failed to Yield Right-of-Way, Other Improper Action'
 'Ran Stop Sign'
 'Improper Backing, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action, Ran Off Roadway, Too Fast For Conditions'
 'Too Fast For Conditions'
 'Failed to Keep in Proper Lane, Over-Correcting/Over-Steering, Ran Off Roadway'
 'Failed to Yield Right-of-Way, Ran Stop Sign'
 'Failed to Keep in Proper Lane, Improper Turn'
 'Followed Too Closely, Over-Correcting/Over-Steering'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Over-Correcting/Over-Steering'
 'Ran Red Light, Too Fast For Conditions'
 'Other Improper Action, Too Fast For Conditions'
 'Improper Passing, Other Improper Action'
 'Failed to Yield Right-of-Way, Improper Turn'
 'Failed to Keep in Proper Lane, Failed to Yield Right-of-Way, Ran Red Light'
 'Failed to Yield Right-of-Way, Ran Red Light'
 'Failed to Keep in Proper Lane, Improper Passing'
 'Followed Too Closely, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner'
 'Disregarded Other Road Markings, Disregarded Other Traffic Sign, Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Ran Red Light'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action, Too Fast For Conditions'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner'
 'Failed to Keep in Proper Lane, Failed to Yield Right-of-Way'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action'
 'Failed to Keep in Proper Lane, Improper Passing, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Over-Correcting/Over-Steering, Ran Off Roadway, Too Fast For Conditions, Wrong Side'
 'Other Improper Action, Ran Off Roadway, Too Fast For Conditions'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Ran Red Light, Too Fast For Conditions'
 'Disregarded Other Road Markings, Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action'
 'Improper Passing, Wrong Side'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action'
 'Disregarded Other Traffic Sign, Failed to Yield Right-of-Way'
 'Over-Correcting/Over-Steering, Ran Off Roadway'
 'Disregarded Other Traffic Sign'
 'Over-Correcting/Over-Steering, Swerved or Avoided Due to Wind, Slippery Surface, Motor Vehicle, Object, Non-Motorist in Roadway, etc'
 'Disregarded Other Road Markings, Too Fast For Conditions'
 'Disregarded Other Road Markings, Disregarded Other Traffic Sign, Failed to Keep in Proper Lane, Improper Turn, Wrong Side'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action, Over-Correcting/Over-Steering, Too Fast For Conditions'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action, Ran Off Roadway, Ran Red Light'
 'Failed to Keep in Proper Lane, Improper Turn, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Over-Correcting/Over-Steering, Too Fast For Conditions, Wrong Side'
 'Over-Correcting/Over-Steering, Too Fast For Conditions'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Ran Red Light'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner'
 'Failed to Keep in Proper Lane, Other Improper Action, Ran Off Roadway, Wrong Side'
 'Improper Turn, Ran Off Roadway'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Reckless or Aggressive Manner, Too Fast For Conditions'
 'Improper Passing, Improper Turn'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action, Too Fast For Conditions'
 'Operated Motor Vehicle in Reckless or Aggressive Manner, Too Fast For Conditions'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action'
 'Other Improper Action, Ran Off Roadway'
 'Failed to Yield Right-of-Way, Improper Passing, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Too Fast For Conditions'
 'Ran Off Roadway, Too Fast For Conditions'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Ran Off Roadway'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action, Over-Correcting/Over-Steering'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Ran Red Light'
 'Failed to Keep in Proper Lane, Wrong Side'
 'Other Improper Action, Over-Correcting/Over-Steering, Ran Off Roadway, Too Fast For Conditions'
 'Disregarded Other Road Markings, Disregarded Other Traffic Sign, Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action'
 'Disregarded Other Road Markings, Improper Turn'
 'Improper Backing, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Too Fast For Conditions'
 'Failed to Keep in Proper Lane, Over-Correcting/Over-Steering, Wrong Side'
 'Improper Turn, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Too Fast For Conditions, Wrong Side'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action'
 'Disregarded Other Traffic Sign, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Wrong Side'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action, Ran Off Roadway'
 'Disregarded Other Road Markings, Failed to Keep in Proper Lane, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action, Too Fast For Conditions, Wrong Side'
 'Ran Off Roadway, Wrong Side'
 'Failed to Keep in Proper Lane, Over-Correcting/Over-Steering, Ran Off Roadway, Too Fast For Conditions, Wrong Side'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Too Fast For Conditions'
 'Disregarded Other Road Markings, Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Wrong Side'
 'Disregarded Other Road Markings'
 'Disregarded Other Traffic Sign, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Ran Red Light'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action, Too Fast For Conditions'
 'Disregarded Other Traffic Sign, Other Improper Action'
 'Failed to Keep in Proper Lane, Ran Off Roadway, Too Fast For Conditions'
 'Disregarded Other Traffic Sign, Failed to Yield Right-of-Way, Too Fast For Conditions'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Ran Red Light'
 'Failed to Keep in Proper Lane, Improper Passing, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Ran Red Light'
 'Failed to Keep in Proper Lane, Other Improper Action'
 'Disregarded Other Traffic Sign, Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Too Fast For Conditions'
 'Improper Turn, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action, Over-Correcting/Over-Steering, Too Fast For Conditions'
 'Failed to Keep in Proper Lane, Failed to Yield Right-of-Way, Too Fast For Conditions'
 'Wrong Side'
 'Disregarded Other Traffic Sign, Failed to Yield Right-of-Way, Improper Turn, Other Improper Action'
 'Failed to Keep in Proper Lane, Failed to Yield Right-of-Way, Improper Turn, Other Improper Action'
 'Followed Too Closely, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action, Over-Correcting/Over-Steering'
 'Failed to Keep in Proper Lane, Swerved or Avoided Due to Wind, Slippery Surface, Motor Vehicle, Object, Non-Motorist in Roadway, etc'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Ran Off Roadway'
 'Improper Backing, Other Improper Action'
 'Failed to Keep in Proper Lane, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Other Improper Action, Over-Correcting/Over-Steering'
 'Improper Passing, Operated Motor Vehicle in Reckless or Aggressive Manner, Too Fast For Conditions'
 'Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Ran Off Roadway, Ran Red Light'
 'Followed Too Closely, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Other Improper Action'
 'Failed to Yield Right-of-Way, Operated Motor Vehicle in Inattentive, Careless, Negligent, or Erratic Manner, Operated Motor Vehicle in Reckless or Aggressive Manner, Ran Red Light'

In [ ]:
column_list_abridged = ["Agency_Name", "ACRS_Report_Type", "Crash_Date_Time", "Route_Type", "Related_Non_Motorist", "Collision_Type", "Weather", "Surface_Condition", "Ambient_Light", "Traffic_Control", "Driver_Substance_Use", "Non_Motorist_Substance_Use", "Driver_At_Fault", "Injury_Severity", "Circumstance", "Driver_Distraction", "Drivers_License_State", "Vehicle_ID", "Vehicle_Damage", "Veh_1st_Impact_Loc", "Veh_Body_Type", "Vehicle_Movement", "Veh_Going_Dir", "Speed_Limit", "Driverless_Vehicle", "Parked_Vehicle", "Vehicle_Year", "Vehicle_Make", "Veh_Model", "Hit_Run", "Lane_Type", "At Fault", "First_Harmful_Event", "Second_Harmful_Event", "Junction", "Intersection_Type", "Road Alignment", "Road_Condition", "Road_Division","Location"]

In [ ]:
merged_cleaned_df = merged_df[column_list_abridged].copy()
merged_cleaned_df.head()

,Agency_Name,ACRS_Report_Type,Crash_Date_Time,Route_Type,Related_Non_Motorist,Collision_Type,Weather,Surface_Condition,Ambient_Light,Traffic_Control,...,Lane_Type,At Fault,First_Harmful_Event,Second_Harmful_Event,Junction,Intersection_Type,Road Alignment,Road_Condition,Road_Division,Location
0,MONTGOMERY,Injury Crash,5/5/26 22:43,Maryland (State) Route,NaN,Front to Front,Clear,Dry,Dark - Lighted,No Controls,...,Lane 2,DRIVER,Motor Vehicle In Transport,NaN,Non-Junction,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.03271067, -76.98539433)"
1,MONTGOMERY,Injury Crash,5/5/26 22:43,Maryland (State) Route,NaN,Front to Front,Clear,Dry,Dark - Lighted,No Controls,...,Lane 2,DRIVER,Motor Vehicle In Transport,NaN,Non-Junction,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.03271067, -76.98539433)"
2,ROCKVILLE,Property Damage Crash,5/5/26 21:43,Maryland (State) Route,NaN,Front to Rear,Clear,Dry,Dark - Lighted,Flashing Traffic Control Signal,...,Lane 2,UNKNOWN,Motor Vehicle In Transport,Motor Vehicle In Transport,Acceleration/Deceleration Lane,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.07866033, -77.13205117)"
3,ROCKVILLE,Property Damage Crash,5/5/26 21:43,Maryland (State) Route,NaN,Front to Rear,Clear,Dry,Dark - Lighted,Flashing Traffic Control Signal,...,Lane 2,UNKNOWN,Motor Vehicle In Transport,Motor Vehicle In Transport,Acceleration/Deceleration Lane,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.07866033, -77.13205117)"
4,MONTGOMERY,Property Damage Crash,5/5/26 21:30,County Route,NaN,Angle,Clear,Dry,Dark - Lighted,Lane Use Control Signal,...,Lane 1,DRIVER,Motor Vehicle In Transport,Not Applicable,Crossover-Related,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.09698583, -77.00256383)"

In [ ]:
# For all cells in merged_cleaned_df:
# if value in cell == "unkonwn" or "UNKNOWN" or "other" or "OTHER"
# or "Not Applicable" or "NOT APPLICABLE", then set value to nan
values_to_replace = ["unkonwn", "UNKNOWN", "Unknown", "other", "OTHER", "Other","Not Applicable", "NOT APPLICABLE", "not applicable", "na", "NA", "N/A", "n/a"]

for col in merged_cleaned_df.columns:
    if merged_cleaned_df[col].dtype == "object": # Only apply to object (string) columns
        merged_cleaned_df[col] = merged_cleaned_df[col].replace(values_to_replace, np.nan)

display(merged_cleaned_df.head())

,Agency_Name,ACRS_Report_Type,Crash_Date_Time,Route_Type,Related_Non_Motorist,Collision_Type,Weather,Surface_Condition,Ambient_Light,Traffic_Control,...,Lane_Type,At Fault,First_Harmful_Event,Second_Harmful_Event,Junction,Intersection_Type,Road Alignment,Road_Condition,Road_Division,Location
0,Montgomery County Police,Injury Crash,5/5/26 22:43,Maryland (State) Route,NaN,Front to Front,Clear,Dry,Dark - Lighted,No Controls,...,Lane 2,DRIVER,Motor Vehicle In Transport,NaN,Non-Junction,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.03271067, -76.98539433)"
1,Montgomery County Police,Injury Crash,5/5/26 22:43,Maryland (State) Route,NaN,Front to Front,Clear,Dry,Dark - Lighted,No Controls,...,Lane 2,DRIVER,Motor Vehicle In Transport,NaN,Non-Junction,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.03271067, -76.98539433)"
2,Rockville Police Dept,Property Damage Crash,5/5/26 21:43,Maryland (State) Route,NaN,Front to Rear,Clear,Dry,Dark - Lighted,Flashing Traffic Control Signal,...,Lane 2,NaN,Motor Vehicle In Transport,Motor Vehicle In Transport,Acceleration/Deceleration Lane,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.07866033, -77.13205117)"
3,Rockville Police Dept,Property Damage Crash,5/5/26 21:43,Maryland (State) Route,NaN,Front to Rear,Clear,Dry,Dark - Lighted,Flashing Traffic Control Signal,...,Lane 2,NaN,Motor Vehicle In Transport,Motor Vehicle In Transport,Acceleration/Deceleration Lane,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.07866033, -77.13205117)"
4,Montgomery County Police,Property Damage Crash,5/5/26 21:30,County Route,NaN,Angle,Clear,Dry,Dark - Lighted,Lane Use Control Signal,...,Lane 1,DRIVER,Motor Vehicle In Transport,NaN,Crossover-Related,NaN,Straight,No Defects,"Divided, Raised Median (curbed)","(39.09698583, -77.00256383)"

In [ ]:
# merge agency names
merged_cleaned_df["Agency_Name"] = merged_cleaned_df["Agency_Name"].replace({
    "MONTGOMERY" : "Montgomery County Police",
    "Rockville Police Departme" : "Rockville Police Dept",
    "ROCKVILLE" : "Rockville Police Dept",
    "Takoma Park Police Depart" : "Takoma Park Police Dept",
    "TAKOMA" : "Takoma Park Police Dept",
    "Gaithersburg Police Depar" : "Gaithersburg Police Dept",
    "GAITHERSBURG" : "Gaithersburg Police Dept",
    "Maryland-National Capital" : "MD-Natl Capital Park Pol",
    "MCPARK" : "MoCo Park Police"
})
display(merged_cleaned_df["Agency_Name"].unique())

array(['Montgomery County Police', 'Rockville Police Dept',
       'Takoma Park Police Dept', 'Gaithersburg Police Dept',
       'MoCo Park Police', 'MD-Natl Capital Park Pol'], dtype=object)

In [ ]:
for col in merged_cleaned_df.select_dtypes(include='object').columns:
    unique_values = merged_cleaned_df[col].dropna().unique()

    replacement_map = {}
    grouped_values = {}

    # Group values by their lowercase form
    for value in unique_values:
        lower_value = value.lower()
        if lower_value not in grouped_values:
            grouped_values[lower_value] = []
        grouped_values[lower_value].append(value)

    # Create replacement map: all-caps -> first non-all-caps variant
    for lower_key, variants in grouped_values.items():
        all_caps_variants = [v for v in variants if v.isupper()]
        non_all_caps_variants = [v for v in variants if not v.isupper()]

        if non_all_caps_variants and all_caps_variants:
            # Choose the first non-all-caps variant as the target
            target_variant = non_all_caps_variants[0]
            for ac_variant in all_caps_variants:
                if ac_variant != target_variant: # Ensure no self-replacement if target is also all-caps (unlikely with this logic)
                    replacement_map[ac_variant] = target_variant

    if replacement_map: # Only apply replace if there are actual replacements to make
        merged_cleaned_df[col] = merged_cleaned_df[col].replace(replacement_map)
        print(f"Standardized capitalization for column: {col}")

# Display unique values for a few columns to verify the cleaning
print("\nUnique values after capitalization standardization:")
display(merged_cleaned_df["Agency_Name"].unique())
display(merged_cleaned_df["ACRS_Report_Type"].unique())
display(merged_cleaned_df["Weather"].unique())

Unique values after capitalization standardization:

array(['Montgomery County Police', 'Rockville Police Dept',
       'Takoma Park Police Dept', 'Gaithersburg Police Dept',
       'MoCo Park Police', 'MD-Natl Capital Park Pol'], dtype=object)

array(['Injury Crash', 'Property Damage Crash', 'Fatal Crash'],
      dtype=object)

array(['Clear', 'Rain', 'Cloudy', nan, 'Fog, Smog, Smoke',
       'Freezing Rain Or Freezing Drizzle', 'Sleet Or Hail', 'Snow',
       'Blowing Snow', 'Severe Crosswinds', 'Blowing Sand, Soil, Dirt',
       'RAINING', 'FOGGY', 'SLEET', 'WINTRY MIX', 'SEVERE WINDS'],
      dtype=object)


Compare values in each column.
If a value written in all caps has a matching value that is written in mixed case or lower case,
then convert all data written in all caps into the matching version that is written in mixed case or lower case.

In [ ]:
classifiable_columns = ["Agency_Name", "ACRS_Report_Type", "Crash_Date_Time", "Route_Type", "Related_Non_Motorist", "Collision_Type", "Weather", "Surface_Condition", "Ambient_Light", "Traffic_Control", "Driver_Substance_Use", "Non_Motorist_Substance_Use", "Driver_At_Fault", "Injury_Severity", "Driver_Distraction", "Drivers_License_State", "Vehicle_Damage", "Veh_1st_Impact_Loc", "Veh_Body_Type", "Veh_Going_Dir", "Speed_Limit", "Driverless_Vehicle", "Parked_Vehicle", "Vehicle_Year", "Hit_Run", "At Fault", "First_Harmful_Event", "Second_Harmful_Event", "Junction", "Intersection_Type", "Road Alignment", "Road_Condition"]
for i in classifiable_columns:
  print(f"{i} : \n{merged_cleaned_df[i].unique()}\n\n")

Agency_Name :
['Montgomery County Police' 'Rockville Police Dept'
 'Takoma Park Police Dept' 'Gaithersburg Police Dept' 'MoCo Park Police'
 'MD-Natl Capital Park Pol']


ACRS_Report_Type :
['Injury Crash' 'Property Damage Crash' 'Fatal Crash']


Crash_Date_Time :
['5/5/26 22:43' '5/5/26 21:43' '5/5/26 21:30' ... '1/1/15 1:14'
 '1/1/15 1:10' '1/1/15 0:30']


Route_Type :
['Maryland (State) Route' 'County Route' 'Spur' nan 'US (State)'
 'Local Route' 'Municipality Route' 'Other Public Roadway' 'Bicycle Route'
 'Ramp' 'Crossover' 'Interstate (State)' 'Private Route'
 'Government Route' 'Service Road' 'County' 'Maryland (State)'
 'Municipality' 'Government']


Related_Non_Motorist :
[nan 'Cyclist (non-electric)' 'Pedestrian' 'Cyclist (Electric)'
 'Occupant Of a Non-Motor Vehicle Transportation Device'
 'Scooter (non-Electric)' 'Scooter (electric)'
 'Other Pedestrian (person in a building, skater, personal conveyance, etc.)'
 'Wheelchair (electric)' 'Unknown Type Of Non-Motorist'
 'Occupant of Motor Vehicle Not in Transport'
 'Occupant of Motor Vehicle Not in Transport, Pedestrian'
 'Pedestrian, Wheelchair (non-electric)' 'Unknown, Wheelchair (electric)'
 'Wheelchair (non-electric)'
 'Other Pedestrian (person in a building, skater, personal conveyance, etc.), Pedestrian'
 'BICYCLIST' 'MACHINE OPERATOR/RIDER' 'OTHER PEDALCYCLIST'
 'OTHER, PEDESTRIAN' 'OTHER CONVEYANCE' 'OTHER CONVEYANCE, PEDESTRIAN'
 'BICYCLIST, OTHER' 'BICYCLIST, PEDESTRIAN' 'IN ANIMAL-DRAWN VEH'
 'OTHER, OTHER CONVEYANCE']


Collision_Type :
['Front to Front' 'Front to Rear' 'Angle' 'Single Vehicle'
 'Sideswipe, Opposite Direction' nan 'Rear To Side' 'Rear To Rear'
 'Sideswipe, Same Direction' 'OPPOSITE DIRECTION SIDESWIPE'
 'HEAD ON LEFT TURN' 'STRAIGHT MOVEMENT ANGLE' 'SAME DIR REAR END'
 'HEAD ON' 'SAME DIRECTION SIDESWIPE' 'SAME DIRECTION RIGHT TURN'
 'SAME DIRECTION LEFT TURN' 'ANGLE MEETS LEFT TURN'
 'SAME DIR BOTH LEFT TURN' 'SAME DIR REND LEFT TURN'
 'ANGLE MEETS RIGHT TURN' 'OPPOSITE DIR BOTH LEFT TURN'
 'ANGLE MEETS LEFT HEAD ON' 'SAME DIR REND RIGHT TURN']


Weather :
['Clear' 'Rain' 'Cloudy' nan 'Fog, Smog, Smoke'
 'Freezing Rain Or Freezing Drizzle' 'Sleet Or Hail' 'Snow' 'Blowing Snow'
 'Severe Crosswinds' 'Blowing Sand, Soil, Dirt' 'RAINING' 'FOGGY' 'SLEET'
 'WINTRY MIX' 'SEVERE WINDS']


Surface_Condition :
['Dry' nan 'Wet' 'Water (standing, moving)' 'Ice/Frost' 'Slush' 'Snow'
 'Mud, Dirt, Gravel' 'Oil' 'Sand' 'ICE' 'WATER(STANDING/MOVING)']


Ambient_Light :
['Dark - Lighted' 'Dark - Unknown Lighting' 'Daylight'
 'Dark - Not Lighted' 'Dusk' 'Dawn' nan 'DARK NO LIGHTS' 'DARK LIGHTS ON'
 'DARK -- UNKNOWN LIGHTING']


Traffic_Control :
['No Controls' 'Flashing Traffic Control Signal' 'Lane Use Control Signal'
 'Traffic Control Signal' nan 'Intersection Ahead Warning Sign'
 'Stop Sign'
 'Other Pavement Marking (excluding edgelines, centerlines, or lane lines)'
 'Other Signal' 'Pedestrian Crossing Sign' 'Yield Sign' 'School Zone Sign'
 'Other Warning Sign' 'Pedestrian Crossing'
 'Person (including flagger, law enforcement, crossing guard, etc.'
 'Flashing Railroad Crossing Signal (may include gates)'
 'Flashing School Zone Signal' 'Ramp Meter Signal'
 'Reduce Speed Ahead Warning Sign' 'Bicycle Crossing Sign'
 'Curve Ahead Warning Sign' 'Railroad Crossing' 'School Zone'
 'TRAFFIC SIGNAL' 'RAILWAY CROSSING DEVICE' 'FLASHING TRAFFIC SIGNAL'
 'PERSON' 'WARNING SIGN' 'SCHOOL ZONE SIGN DEVICE']


Driver_Substance_Use :
['Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Suspect of Alcohol Use, Not Suspect of Drug Use' 'Unknown, Unknown'
 'Suspect of Alcohol Use, Unknown'
 'Not Suspect of Alcohol Use, Suspect of Drug Use'
 'Suspect of Alcohol Use, Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Unknown' 'Unknown, Not Suspect of Drug Use'
 'Unknown, Suspect of Drug Use' 'NONE DETECTED' nan 'ALCOHOL PRESENT'
 'ALCOHOL CONTRIBUTED' 'ILLEGAL DRUG PRESENT' 'MEDICATION CONTRIBUTED'
 'COMBINATION CONTRIBUTED' 'ILLEGAL DRUG CONTRIBUTED'
 'COMBINED SUBSTANCE PRESENT' 'MEDICATION PRESENT']


Non_Motorist_Substance_Use :
[nan 'Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Unknown, Unknown' 'Not Suspect of Alcohol Use, Suspect of Drug Use'
 'Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Unknown' 'Suspect of Alcohol Use, Unknown'
 'Unknown, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Suspect of Alcohol Use, Suspect of Drug Use'
 'Unknown, Suspect of Drug Use'
 'Unknown, Unknown, Unknown, Not Suspect of Drug Use' 'NONE DETECTED'
 'ALCOHOL PRESENT' 'ALCOHOL CONTRIBUTED'
 'ALCOHOL CONTRIBUTED, ALCOHOL PRESENT' 'N/A, NONE DETECTED'
 'ILLEGAL DRUG PRESENT' 'ILLEGAL DRUG CONTRIBUTED' 'N/A, UNKNOWN'
 'MEDICATION PRESENT' 'COMBINATION CONTRIBUTED' 'NONE DETECTED, UNKNOWN'
 'COMBINED SUBSTANCE PRESENT' 'ALCOHOL PRESENT, NONE DETECTED']


Driver_At_Fault :
['No' 'Yes' nan]


Injury_Severity :
['Suspected Minor Injury' 'No Apparent Injury' nan 'Possible Injury'
 'Suspected Serious Injury' 'Fatal Injury']


Driver_Distraction :
['Not Distracted' nan 'Talking/listening'
 'Other Action (looking away from task, etc.)'
 'Manually Operating (dialing, playing game, etc.)'
 'LOOKED BUT DID NOT SEE' 'OTHER DISTRACTION'
 'OTHER ELECTRONIC DEVICE (NAVIGATIONAL PALM PILOT)'
 'INATTENTIVE OR LOST IN THOUGHT'
 'DISTRACTED BY OUTSIDE PERSON OBJECT OR EVENT' 'EATING OR DRINKING'
 'TALKING OR LISTENING TO CELLULAR PHONE' 'OTHER CELLULAR PHONE RELATED'
 'ADJUSTING AUDIO AND OR CLIMATE CONTROLS'
 'USING DEVICE OBJECT BROUGHT INTO VEHICLE' 'BY OTHER OCCUPANTS'
 'TEXTING FROM A CELLULAR PHONE' 'DIALING CELLULAR PHONE'
 'BY MOVING OBJECT IN VEHICLE' 'NO DRIVER PRESENT'
 'USING OTHER DEVICE CONTROLS INTEGRAL TO VEHICLE' 'SMOKING RELATED']


Drivers_License_State :
['MD' nan 'FL' 'AZ' 'DC' 'MO' 'DE' 'VA' 'NJ' 'WV' 'PA' 'IN' 'NC' 'MN'
 'MX-MEX' 'XX' 'TX' 'SC' 'CA' 'NY' 'US' 'GA' 'AL' 'WA' 'OH' 'CO' 'MA' 'CT'
 'NV' 'SD' 'ME' 'MS' 'MH' 'OR' 'AR' 'IL' 'KY' 'MI' 'NM' 'MP' 'KS' 'TN'
 'LA' 'NE' 'PR' 'VT' 'IA' 'MX-CMX' 'WY' 'UT' 'ID' 'MX-GRO' 'UM' 'HI'
 'CA-ON' 'CA-QC' 'MT' 'GU' 'MX-BCN' 'VI' 'WI' 'NH' 'OK' 'AK' 'MX-ROO' 'ON'
 'QC' 'MB' 'AB' 'ND' 'NF' 'IT' 'RI' 'NB' 'BC' 'NL' 'YT' 'FM' 'AS' 'SK'
 'NS' 'NT']


Vehicle_Damage :
['Disabling' 'Functional' 'Vehicle Not at Scene' 'Superficial' 'No Damage'
 nan 'DESTROYED']


Veh_1st_Impact_Loc :
['One O Clock' 'Six O Clock' 'Twelve O Clock' 'Two O Clock'
 'Vehicle Not at Scene' 'Eleven O Clock' 'Nine O Clock' 'Eight O Clock'
 'Seven O Clock' 'Five O Clock' 'Non-Collision' 'Ten O Clock'
 'Three O Clock' 'Four O Clock' 'Underside' 'Top' 'Cargo Loss'
 'EIGHT OCLOCK' 'SEVEN OCLOCK' 'TWELVE OCLOCK' nan 'ONE OCLOCK'
 'SIX OCLOCK' 'TEN OCLOCK' 'FOUR OCLOCK' 'TWO OCLOCK' 'ELEVEN OCLOCK'
 'THREE OCLOCK' 'NINE OCLOCK' 'FIVE OCLOCK' 'ROOF TOP']


Veh_Body_Type :
['Passenger Car' 'Sport Utility Vehicle' nan 'Single-Unit Truck'
 'Motorcycle - 2 Wheeled' 'Bus - School' 'Truck Tractor'
 'Van - Passenger (&lt;9 Seats)' 'Pickup' 'Station Wagon' 'Other Trucks'
 'Moped Or motorized bicycle' 'Bus - Transit' 'Van - Cargo'
 'Van - Passenger (9 or 12 Seats)' 'Bus - Mini' 'Low Speed Vehicle'
 'Autocycle' 'Golf Cart' 'All-Terrain Vehicle/All-Terrain Cycle (ATV/ATC)'
 'Bus - Other Type' 'Construction Equipment (backhoe, bulldozer, etc.)'
 'Snowmobile' 'Motor Home' 'Recreational Off-Highway Vehicles (ROV)'
 'Van - Passenger (15 Seats)'
 'Farm Equipment (Tractor, combine harvester, etc.)' 'Bus - Cross Country'
 'Motorcycle - 3 Wheeled' 'SCHOOL BUS' '(SPORT) UTILITY VEHICLE'
 'TRANSIT BUS' 'VAN' 'AMBULANCE/EMERGENCY' 'AMBULANCE/NON EMERGENCY'
 'PICKUP TRUCK' 'POLICE VEHICLE/EMERGENCY'
 'CARGO VAN/LIGHT TRUCK 2 AXLES (OVER 10,000LBS (4,536 KG))'
 'OTHER LIGHT TRUCKS (10,000LBS (4,536KG) OR LESS)'
 'FIRE VEHICLE/EMERGENCY' 'POLICE VEHICLE/NON EMERGENCY' 'MOPED'
 'FIRE VEHICLE/NON EMERGENCY' 'RECREATIONAL VEHICLE'
 'MEDIUM/HEAVY TRUCKS 3 AXLES (OVER 10,000LBS (4,536KG))' 'MOTORCYCLE'
 'ALL TERRAIN VEHICLE (ATV)' 'OTHER BUS' 'CROSS COUNTRY BUS'
 'FARM VEHICLE' 'LIMOUSINE']


Veh_Going_Dir :
['Southbound' 'Northbound' 'Eastbound' 'Westbound' nan 'Not On Roadway'
 'North' 'South' 'West' 'East']


Speed_Limit :
[40 35 25 45 30  0 15  5 55 50 20 10 60 75 65 70]


Driverless_Vehicle :
['No' nan]


Parked_Vehicle :
['No' 'Yes' nan]


Vehicle_Year :
[2018. 2026. 2023. 2005. 2025. 2020.   nan 2009. 2011. 2024. 2016. 2014.
 2006. 2013. 2019. 2017. 2015. 2010. 2008. 2021. 2012. 2022. 1987. 1999.
 2003. 1998. 2001. 2004. 2002. 2007. 2000. 1992. 1983. 1966. 1997. 1996.
 1980. 1993. 1990. 1995. 1986. 1989. 1994. 1984. 1988. 1977. 1985. 1968.
 1991. 1967. 1957. 1978. 1981. 1938. 1982. 1974. 1961. 1976. 1969. 1930.
 1965. 1979. 1972. 1955. 1971. 1970. 1959. 1947. 1946. 1949. 1975. 1960.
 1963.]


Hit_Run :
['No' 'Yes' nan]


At Fault :
['DRIVER' nan 'NONMOTORIST' 'BOTH']


First_Harmful_Event :
['Motor Vehicle In Transport' 'Pedalcycle' 'Pedestrian' 'Fence'
 'Parked Vehicle' 'Curb' 'Tree (standing)' 'Other Post, Pole, Or Support'
 'Guardrail Face' 'Utility Pole/Light Support' 'Concrete Traffic Barrier'
 'Traffic Sign Support'
 'Other Fixed Object (wall, building, tunnel, etc.)'
 'Other Non-Fixed Object' 'Animal (live)' 'Other Non-Motorist'
 'Traffic Signal Support' 'Mailbox' 'Other Traffic Barrier' 'Ditch' nan
 'Overturn/Rollover' 'Fell Jumped from Motor Vehicle'
 'Other Non-Collision' 'Bridge Pier Or Support' 'Embankment'
 'Cable Barrier' 'Guardrail End Terminal'
 'Railway Vehicle (train, engine)' 'Culvert' 'Thrown Or Falling Object'
 'Bridge Rail' 'Explosion Or Fire' 'Spilled Cargo'
 'Strikes Object at Rest from Motor Vehicle In Transport'
 'Struck by Falling, Shifting Cargo Or Anything Set In Motion by Motor Vehicle'
 'Construction Equipment' 'Impact Attenuator/Crash Cushion'
 'Bridge Overhead Structure' 'Units Separated'
 'Cargo/Equipment Loss Or Shift' 'Jackknife' 'OTHER VEHICLE' 'OFF ROAD'
 'FIXED OBJECT' 'OTHER OBJECT' 'ANIMAL' 'BICYCLE' 'OVERTURN' 'BACKING'
 'OTHER NON COLLISION' 'OTHER CONVEYANCE' 'RAILWAY TRAIN'
 'OTHER PEDALCYCLE' 'U-TURN' 'DOWNHILL RUNAWAY' 'IMMERSION']


Second_Harmful_Event :
[nan 'Motor Vehicle In Transport' 'Tree (standing)' 'Parked Vehicle'
 'Traffic Sign Support' 'Other Post, Pole, Or Support' 'Curb'
 'Overturn/Rollover' 'Fence'
 'Other Fixed Object (wall, building, tunnel, etc.)' 'Pedestrian' 'Ditch'
 'Strikes Object at Rest from Motor Vehicle In Transport'
 'Traffic Signal Support' 'Utility Pole/Light Support' 'Guardrail Face'
 'Embankment' 'Other Non-Motorist' 'Cable Barrier' 'Mailbox'
 'Explosion Or Fire' 'Concrete Traffic Barrier' 'Other Traffic Barrier'
 'Other Non-Fixed Object' 'Animal (live)' 'Other Non-Collision'
 'Pedalcycle'
 'Struck by Falling, Shifting Cargo Or Anything Set In Motion by Motor Vehicle'
 'Guardrail End Terminal' 'Fell Jumped from Motor Vehicle'
 'Thrown Or Falling Object' 'Construction Equipment' 'Culvert'
 'Bridge Rail' 'Spilled Cargo' 'Jackknife' 'Units Separated'
 'Impact Attenuator/Crash Cushion' 'Immersion, Full or Partial'
 'Railway Vehicle (train, engine)' 'FIXED OBJECT' 'OTHER NON COLLISION'
 'OTHER VEHICLE' 'OVERTURN' 'OFF ROAD' 'OTHER OBJECT' 'OTHER CONVEYANCE'
 'DOWNHILL RUNAWAY' 'ANIMAL' 'BICYCLE' 'BACKING' 'U-TURN' 'IMMERSION'
 'OTHER PEDALCYCLE']


Junction :
['Non-Junction' 'Acceleration/Deceleration Lane' 'Crossover-Related'
 'Intersection or Related' 'Entrance/Exit Ramp or Related' nan
 'Through Roadway' 'Driveway Access or Related'
 'Other Location Not Listed Above Within an Interchange Area (median,\nshoulder and roadside)'
 'Shared-Use Path or Trail' 'Railway Grade Crossing' 'INTERSECTION'
 'NON INTERSECTION' 'INTERSECTION RELATED' 'OTHER DRIVEWAY'
 'INTERCHANGE RELATED' 'COMMERCIAL DRIVEWAY' 'CROSSOVER RELATED'
 'RESIDENTIAL DRIVEWAY' 'ALLEY']


Intersection_Type :
[nan 'Perpendicular' 'Angled/Skewed' 'Roundabout/Traffic Circle'
 'FOUR-WAY INTERSECTION' 'T-INTERSECTION' 'FIVE-POINT OR MORE'
 'Y-INTERSECTION' 'ROUNDABOUT' 'TRAFFIC CIRCLE']


Road Alignment :
['Straight' nan 'Curve Left' 'Curve Left, Straight' 'Curve Right'
 'Curve Left, Curve Right' 'Curve Right, Straight'
 'Curve Left, Curve Right, Straight']


Road_Condition :
['No Defects' nan 'Holes Ruts Etc' 'Foreign Material'
 'Loose Surface Material' 'View Obstructed' 'Obstruction Not Signaled'
 'Shoulder Defect' 'Obstruction Not Lighted']

In [ ]:
merged_cleaned_df.nunique()

Agency_Name                        6
ACRS_Report_Type                   3
Crash_Date_Time               117933
Route_Type                        18
Related_Non_Motorist              25
Collision_Type                    23
Weather                           15
Surface_Condition                 11
Ambient_Light                      9
Traffic_Control                   28
Driver_Substance_Use              18
Non_Motorist_Substance_Use        25
Driver_At_Fault                    2
Injury_Severity                    5
Circumstance                     854
Driver_Distraction                21
Drivers_License_State             81
Vehicle_ID                    214273
Vehicle_Damage                     6
Veh_1st_Impact_Loc                30
Veh_Body_Type                     50
Vehicle_Movement                  25
Veh_Going_Dir                      9
Speed_Limit                       16
Driverless_Vehicle                 1
Parked_Vehicle                     2
Vehicle_Year                      72
Vehicle_Make                    1963
Veh_Model                       7191
Hit_Run                            2
Lane_Type                        197
At Fault                           3
First_Harmful_Event               56
Second_Harmful_Event              53
Junction                          19
Intersection_Type                  9
Road Alignment                     7
Road_Condition                     8
Road_Division                     33
Location                      120115
dtype: int64

In [ ]:
merged_cleaned_df.to_csv("crash_data_cleaned_full")

Some categorical variables need to be cleaned up severely.  
This is for another time:  
- Related_Non_Motorist  
- Lane_Type
- Road_Division : caseblind,
Drivers_License_State : nan = "XX", "MX-MEX", "MX-MX-ROO", "MX-GRO" = Mex,
CA-ON, CA-QC, ON, QC, BC = Can



 caseblind,

To be cleaned up now:  
- "Agency_Name"
- "Intersection_Type"  

- Lane_Type to Parking_Lot Y/N/nan  
check against off road

- Vehicle_Damage:  caseblind, "unkonwn" = "other" = nan

Veh_1st_Impact_Loc : "ROOF TOP" = "roof" = "top"; caseblind; OCLOCK = O Clock to O"Clock

- Driver_Distraction:  Unknown = UNKNOWN = "NO DRIVER PRESENT" nan

- "Collision_Type"  "other" = "unknown" = nan

- Veh_Body_Type : caseblind,  unknown = other,

Vehicle_Movement : unknown = nan

- First_Harmful_Event : make caseblind, "Not Applicable" = nan  
- Second_Harmful_Event :  make caseblind, "Not Applicable" = nan  

- Junction : "Non-Junction" =  "NON INTERSECTION" = "UNKNOWN"  = nan

- Intersection_Type : "UNKNOWN"  = nan ;   
"Roundabout/Traffic Circle" = "ROUNDABOUT" = "TRAFFIC CIRCLE"

- Road Alignment: "OTHER" "UNKNOWN" = nan;  make caseblind

- Road_Condition:  "Unknown" nan; caseblind
  
Not useful or meaning unclear.  Discard:  
- Road_Grade
- Lane_Direction

####Categorical Data:
ACRS_Report_Type : ['Injury Crash' 'Property Damage Crash' 'Fatal Crash']



####Date/Time:
Date_Time

####Log of changes made to datasets:

Drivers:
- added underscores in column names to remove spaces
- abbreviated some column names
- deleted "location" column (already have latitude, longitude)
- deleted Local Case Number (Report Number is already identifier)

Incidents:
- added underscores in column names to remove spaces
- abbreviated some column names
- deleted "direction", "distance", "distance unit columns"  
due to contradiction of definitions in sources
- deleted Municipality (Blank)
- Number of Lanes (many contain 2 values)

Merged:
- Standardized Vehicle_Year column input years to four-digit
e.g. merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(4, 2004)

---------------
####Future research:  
It would be useful to interview representatives of the municipalities about how they classify and record specific details about crashes, such as drug and alcohol use.  
I would also like to know why the handbook lists many more fields in covered by the Automated Crash Reporting System (ACRS)

Maryland Department of State Police
https://mdsp.maryland.gov/Pages/Dashboards/CrashDataDashboard.aspx  
Maryland Crash Data 2024-Present
Map  
Uses updated information, but that information is not shared with the public (only the preliminary information, which may be incomplete or contain errors for the reasons listed).

Age of driver

Include data about passengers:  number of passengers, general age
------------

####Note on Data
In trying to understand the meaning of certain fields, I may have found an error in the Incidents data description on  
https://data.montgomerycountymd.gov/Public-Safety/Crash-Reporting-Incidents-Data/bhju-22kf/about_data  
The "Direction" field is described as "Location - Direction from mile point."  
The "Distance" field is described as "Location - Distance from mile point."  

However, the Maryland Automated Crash Reporting System (ACRS) Field Reference Guide published on  
https://www.nhtsa.gov/sites/nhtsa.gov/files/documents/acrsfieldreference.pdf
(2017 Maryland State Police)  
section 2.19 states:  
"Distance
Definition:
The distance from the referenced Intersecting Road to the crash site.
Explanation:
The distance in feet or miles from the Intersecting Road to crash site."

Section 2.21:  
"Distance Direction
Definition:
The compass direction describing the direction going from the primary and intersecting
roads to the crash.
Explanation:
Units are described in compass points, i.e. North, South East and West. If the crash
occurred in the intersection, select the compass point referenced in the Mile Point
Direction box above."
---------------------

####About Data

Crash Reporting - Incidents Data  
Original data:  
122,000 Rows  
37 Columns  
Each row is a "Collision"

https://data.montgomerycountymd.gov/Public-Safety/Crash-Reporting-Incidents-Data/bhju-22kf/about_data  

"This dataset provides general information about each collision and details of all traffic collisions occurring on county and local roadways within Montgomery County, as collected via the Automated Crash Reporting System (ACRS) of the Maryland State Police, and reported by the Montgomery County Police, Gaithersburg Police, Rockville Police, or the Maryland-National Capital Park Police.

Please note that these collision reports are based on preliminary information supplied to the Police Department by the reporting parties. Therefore, the collision data available on this web page may reflect:

-Information not yet verified by further investigation  
-Information that may include verified and unverified collision data  
-Preliminary collision classifications may be changed at a later date based   upon further investigation  
-Information may include mechanical or human error"

"3.38 Going Direction
Definition:
The direction of the motor vehicles travel on the roadway prior to the crash.
Explanation:
This is not necessarily a compass direction, but must be consistent with the "Distance
Direction" from the Log Mile Information for this roadway."


![crash map disclaimer](https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/main/final/crash_map_disclaimer.png)

AI usage tracker:

- For all cells in merged_cleaned_df:
if value in cell == "unkonwn" or "UNKNOWN" or "other" or "OTHER" or "Not Applicable" or "NOT APPLICABLE",  
set value to nan  

- Compare values in each column.  
If a value written in all caps has a matching value that is written in mixed case or lower case,  
then convert all data written in all caps into the matching version that is written in mixed case or lower case.

In [ ]:
# # Fix vehicle year from 0 to NaN
# # replaced selected, because used describe() to see minimum year
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(0, np.nan)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(1, 2001)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(2, 2002)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(3, 2003)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(4, 2004)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(5, 2005)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(8, 2008)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(13, 2013)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(14, 2014)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(15, 2015)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(97, 1997)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(99, 1999)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(198, 1998)
# # BMW 328 per report was in production 1936-1940
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(200, 1940)
# # Mazda CX-7 was in production 2006-2012
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(201, 2011)
# # Chevy Subruban in production since 1934. impossible to extrapolate year
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(202, np.nan)
#                                 # temporarily change 215 to 2015 for Lexus ES 350
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(215, 2015)
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(999, 1999)
# #Mercedez-Benz C-class in production since 1993. Accident in 2024. 2000 doesn't make sense
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(1000, np.nan)
# #Toyota camry accident in 2016
# merged_df["Vehicle_Year"] = merged_df["Vehicle_Year"].replace(1005, 1995)

# #TODO:  re-check Lexus 2015