crash_df_manip.ipynb vs crash_data_compact.ipynb:
- columns with data that is infeasible to clean within the scope of this project or that will not be used here are removed.  
Larger dataset is provided  
crash_data_cleaned_full.csv  
is in  
https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/main/final/crash_data_cleaned_full.csv

Columns removed from crash_data_cleaned_full.csv:
- Second_Harmful_Event
- Driverless_Vehicle (no such vehicles)
- Veh_Going_Dir
- Route_Type
-
- sort ascending by date of Number, then assign new entry index in lieu of Vehicle_ID

In [2]:
import pandas as pd             # For handling data (DataFrame)
import seaborn as sns           # For visualizations and Planets dataset
import numpy as np              # For numerical operations
# import matplotlib.pyplot as plt # For plots
# import math

# from pandas import plotting

# import statsmodels.formula.api as smf
# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import mean_squared_error, r2_score

In [22]:
crash_compact_df = pd.read_csv(
    "https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/main/final/crash_data_cleaned_full.csv",
    usecols = lambda x: x not in ["Second_Harmful_Event", "Driverless_Vehicle", "Veh_Going_Dir", "Route_Type",])

#crash_compact_df.head()

In [23]:
# rename "Unnamed: 0" col to "Vehicle_Num"
# since Vehicle_ID & Person_ID removed for privacy, need new key
crash_compact_df = crash_compact_df.rename(columns={"Unnamed: 0": "Vehicle_Num"})
#display(crash_compact_df.head())

In [28]:
crash_compact_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214273 entries, 0 to 214272
Data columns (total 37 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Vehicle_Num                 214273 non-null  int64
 1   Agency_Name                 214273 non-null  object
 2   ACRS_Report_Type            214273 non-null  object
 3   Crash_Date_Time             214273 non-null  object
 4   Related_Non_Motorist        6767 non-null    object
 5   Collision_Type              191162 non-null  object
 6   Weather                     199566 non-null  object
 7   Surface_Condition           189141 non-null  object
 8   Ambient_Light               211494 non-null  object
 9   Traffic_Control             182332 non-null  object
 10  Driver_Substance_Use        170904 non-null  object
 11  Non_Motorist_Substance_Use  5654 non-null    object
 12  Driver_At_Fault             209591 non-null  object
 13  Injury_Severity             211299 non-null  object
 14  Circumstance                41805 non-null   object
 15  Driver_Distraction          168451 non-null  object
 16  Drivers_License_State       199506 non-null  object
 17  Vehicle_ID                  214273 non-null  object
 18  Vehicle_Damage              207235 non-null  object
 19  Veh_1st_Impact_Loc          211035 non-null  object
 20  Veh_Body_Type               207845 non-null  object
 21  Vehicle_Movement            208770 non-null  object
 22  Speed_Limit                 214273 non-null  int64
 23  Parked_Vehicle              212747 non-null  object
 24  Vehicle_Year                208779 non-null  float64
 25  Vehicle_Make                209271 non-null  object
 26  Veh_Model                   208449 non-null  object
 27  Hit_Run                     206361 non-null  object
 28  Lane_Type                   51324 non-null   object
 29  At Fault                    190990 non-null  object
 30  First_Harmful_Event         212827 non-null  object
 31  Junction                    167566 non-null  object
 32  Intersection_Type           101990 non-null  object
 33  Road Alignment              192613 non-null  object
 34  Road_Condition              183209 non-null  object
 35  Road_Division               190116 non-null  object
 36  Location                    214273 non-null  object
dtypes: float64(1), int64(2), object(34)
memory usage: 60.5+ MB

In [ ]:
crash_compact_df.nunique()

Unnamed: 0                    214273
Agency_Name                        6
ACRS_Report_Type                   3
Crash_Date_Time               117933
Related_Non_Motorist              25
Collision_Type                    23
Weather                           15
Surface_Condition                 11
Ambient_Light                      9
Traffic_Control                   28
Driver_Substance_Use              18
Non_Motorist_Substance_Use        25
Driver_At_Fault                    2
Injury_Severity                    5
Circumstance                     854
Driver_Distraction                21
Drivers_License_State             81
Vehicle_ID                    214273
Vehicle_Damage                     6
Veh_1st_Impact_Loc                30
Veh_Body_Type                     50
Vehicle_Movement                  25
Speed_Limit                       16
Parked_Vehicle                     2
Vehicle_Year                      72
Vehicle_Make                    1963
Veh_Model                       7191
Hit_Run                            2
Lane_Type                        197
At Fault                           3
First_Harmful_Event               56
Junction                          19
Intersection_Type                  9
Road Alignment                     7
Road_Condition                     8
Road_Division                     33
Location                      120115
dtype: int64

In [24]:
column_list = crash_compact_df.columns.tolist()
print(column_list)

['Vehicle_Num', 'Agency_Name', 'ACRS_Report_Type', 'Crash_Date_Time', 'Related_Non_Motorist', 'Collision_Type', 'Weather', 'Surface_Condition', 'Ambient_Light', 'Traffic_Control', 'Driver_Substance_Use', 'Non_Motorist_Substance_Use', 'Driver_At_Fault', 'Injury_Severity', 'Circumstance', 'Driver_Distraction', 'Drivers_License_State', 'Vehicle_ID', 'Vehicle_Damage', 'Veh_1st_Impact_Loc', 'Veh_Body_Type', 'Vehicle_Movement', 'Speed_Limit', 'Parked_Vehicle', 'Vehicle_Year', 'Vehicle_Make', 'Veh_Model', 'Hit_Run', 'Lane_Type', 'At Fault', 'First_Harmful_Event', 'Junction', 'Intersection_Type', 'Road Alignment', 'Road_Condition', 'Road_Division', 'Location']

In [25]:
column_list_culled = ["Vehicle_Num", "Agency_Name", "ACRS_Report_Type", "Crash_Date_Time", "Related_Non_Motorist", "Collision_Type", "Weather", "Surface_Condition", "Ambient_Light", "Traffic_Control", "Driver_Substance_Use", "Non_Motorist_Substance_Use", "Driver_At_Fault", "Injury_Severity", "Driver_Distraction", "Drivers_License_State", "Vehicle_Damage", "Veh_1st_Impact_Loc", "Veh_Body_Type", "Speed_Limit", "Parked_Vehicle", "Vehicle_Year", "Hit_Run", "Lane_Type", "At Fault", "First_Harmful_Event", "Junction", "Intersection_Type", "Road Alignment", "Road_Condition"]

In [26]:
crash_culled_df = crash_compact_df[column_list_culled].copy()
column_list_2 = crash_culled_df.columns.tolist()
print(column_list_2)

['Vehicle_Num', 'Agency_Name', 'ACRS_Report_Type', 'Crash_Date_Time', 'Related_Non_Motorist', 'Collision_Type', 'Weather', 'Surface_Condition', 'Ambient_Light', 'Traffic_Control', 'Driver_Substance_Use', 'Non_Motorist_Substance_Use', 'Driver_At_Fault', 'Injury_Severity', 'Driver_Distraction', 'Drivers_License_State', 'Vehicle_Damage', 'Veh_1st_Impact_Loc', 'Veh_Body_Type', 'Speed_Limit', 'Parked_Vehicle', 'Vehicle_Year', 'Hit_Run', 'Lane_Type', 'At Fault', 'First_Harmful_Event', 'Junction', 'Intersection_Type', 'Road Alignment', 'Road_Condition']

In [27]:
# run only once
for i in crash_culled_df :
  print(f"{i} : \n{crash_culled_df [i].unique()}\n\n")

Vehicle_Num :
[     0      1      2 ... 214270 214271 214272]


Agency_Name :
['Montgomery County Police' 'Rockville Police Dept'
 'Takoma Park Police Dept' 'Gaithersburg Police Dept' 'MoCo Park Police'
 'MD-Natl Capital Park Pol']


ACRS_Report_Type :
['Injury Crash' 'Property Damage Crash' 'Fatal Crash']


Crash_Date_Time :
['5/5/26 22:43' '5/5/26 21:43' '5/5/26 21:30' ... '1/1/15 1:14'
 '1/1/15 1:10' '1/1/15 0:30']


Related_Non_Motorist :
[nan 'Cyclist (non-electric)' 'Pedestrian' 'Cyclist (Electric)'
 'Occupant Of a Non-Motor Vehicle Transportation Device'
 'Scooter (non-Electric)' 'Scooter (electric)'
 'Other Pedestrian (person in a building, skater, personal conveyance, etc.)'
 'Wheelchair (electric)' 'Unknown Type Of Non-Motorist'
 'Occupant of Motor Vehicle Not in Transport'
 'Occupant of Motor Vehicle Not in Transport, Pedestrian'
 'Pedestrian, Wheelchair (non-electric)' 'Unknown, Wheelchair (electric)'
 'Wheelchair (non-electric)'
 'Other Pedestrian (person in a building, skater, personal conveyance, etc.), Pedestrian'
 'BICYCLIST' 'MACHINE OPERATOR/RIDER' 'OTHER PEDALCYCLIST'
 'OTHER, PEDESTRIAN' 'OTHER CONVEYANCE' 'OTHER CONVEYANCE, PEDESTRIAN'
 'BICYCLIST, OTHER' 'BICYCLIST, PEDESTRIAN' 'IN ANIMAL-DRAWN VEH'
 'OTHER, OTHER CONVEYANCE']


Collision_Type :
['Front to Front' 'Front to Rear' 'Angle' 'Single Vehicle'
 'Sideswipe, Opposite Direction' nan 'Rear To Side' 'Rear To Rear'
 'Sideswipe, Same Direction' 'OPPOSITE DIRECTION SIDESWIPE'
 'HEAD ON LEFT TURN' 'STRAIGHT MOVEMENT ANGLE' 'SAME DIR REAR END'
 'HEAD ON' 'SAME DIRECTION SIDESWIPE' 'SAME DIRECTION RIGHT TURN'
 'SAME DIRECTION LEFT TURN' 'ANGLE MEETS LEFT TURN'
 'SAME DIR BOTH LEFT TURN' 'SAME DIR REND LEFT TURN'
 'ANGLE MEETS RIGHT TURN' 'OPPOSITE DIR BOTH LEFT TURN'
 'ANGLE MEETS LEFT HEAD ON' 'SAME DIR REND RIGHT TURN']


Weather :
['Clear' 'Rain' 'Cloudy' nan 'Fog, Smog, Smoke'
 'Freezing Rain Or Freezing Drizzle' 'Sleet Or Hail' 'Snow' 'Blowing Snow'
 'Severe Crosswinds' 'Blowing Sand, Soil, Dirt' 'RAINING' 'FOGGY' 'SLEET'
 'WINTRY MIX' 'SEVERE WINDS']


Surface_Condition :
['Dry' nan 'Wet' 'Water (standing, moving)' 'Ice/Frost' 'Slush' 'Snow'
 'Mud, Dirt, Gravel' 'Oil' 'Sand' 'ICE' 'WATER(STANDING/MOVING)']


Ambient_Light :
['Dark - Lighted' 'Dark - Unknown Lighting' 'Daylight'
 'Dark - Not Lighted' 'Dusk' 'Dawn' nan 'DARK NO LIGHTS' 'DARK LIGHTS ON'
 'DARK -- UNKNOWN LIGHTING']


Traffic_Control :
['No Controls' 'Flashing Traffic Control Signal' 'Lane Use Control Signal'
 'Traffic Control Signal' nan 'Intersection Ahead Warning Sign'
 'Stop Sign'
 'Other Pavement Marking (excluding edgelines, centerlines, or lane lines)'
 'Other Signal' 'Pedestrian Crossing Sign' 'Yield Sign' 'School Zone Sign'
 'Other Warning Sign' 'Pedestrian Crossing'
 'Person (including flagger, law enforcement, crossing guard, etc.'
 'Flashing Railroad Crossing Signal (may include gates)'
 'Flashing School Zone Signal' 'Ramp Meter Signal'
 'Reduce Speed Ahead Warning Sign' 'Bicycle Crossing Sign'
 'Curve Ahead Warning Sign' 'Railroad Crossing' 'School Zone'
 'TRAFFIC SIGNAL' 'RAILWAY CROSSING DEVICE' 'FLASHING TRAFFIC SIGNAL'
 'PERSON' 'WARNING SIGN' 'SCHOOL ZONE SIGN DEVICE']


Driver_Substance_Use :
['Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Suspect of Alcohol Use, Not Suspect of Drug Use' 'Unknown, Unknown'
 'Suspect of Alcohol Use, Unknown'
 'Not Suspect of Alcohol Use, Suspect of Drug Use'
 'Suspect of Alcohol Use, Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Unknown' 'Unknown, Not Suspect of Drug Use'
 'Unknown, Suspect of Drug Use' 'NONE DETECTED' nan 'ALCOHOL PRESENT'
 'ALCOHOL CONTRIBUTED' 'ILLEGAL DRUG PRESENT' 'MEDICATION CONTRIBUTED'
 'COMBINATION CONTRIBUTED' 'ILLEGAL DRUG CONTRIBUTED'
 'COMBINED SUBSTANCE PRESENT' 'MEDICATION PRESENT']


Non_Motorist_Substance_Use :
[nan 'Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Unknown, Unknown' 'Not Suspect of Alcohol Use, Suspect of Drug Use'
 'Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Unknown' 'Suspect of Alcohol Use, Unknown'
 'Unknown, Not Suspect of Drug Use'
 'Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use, Not Suspect of Alcohol Use, Not Suspect of Drug Use'
 'Suspect of Alcohol Use, Suspect of Drug Use'
 'Unknown, Suspect of Drug Use'
 'Unknown, Unknown, Unknown, Not Suspect of Drug Use' 'NONE DETECTED'
 'ALCOHOL PRESENT' 'ALCOHOL CONTRIBUTED'
 'ALCOHOL CONTRIBUTED, ALCOHOL PRESENT' 'N/A, NONE DETECTED'
 'ILLEGAL DRUG PRESENT' 'ILLEGAL DRUG CONTRIBUTED' 'N/A, UNKNOWN'
 'MEDICATION PRESENT' 'COMBINATION CONTRIBUTED' 'NONE DETECTED, UNKNOWN'
 'COMBINED SUBSTANCE PRESENT' 'ALCOHOL PRESENT, NONE DETECTED']


Driver_At_Fault :
['No' 'Yes' nan]


Injury_Severity :
['Suspected Minor Injury' 'No Apparent Injury' nan 'Possible Injury'
 'Suspected Serious Injury' 'Fatal Injury']


Driver_Distraction :
['Not Distracted' nan 'Talking/listening'
 'Other Action (looking away from task, etc.)'
 'Manually Operating (dialing, playing game, etc.)'
 'LOOKED BUT DID NOT SEE' 'OTHER DISTRACTION'
 'OTHER ELECTRONIC DEVICE (NAVIGATIONAL PALM PILOT)'
 'INATTENTIVE OR LOST IN THOUGHT'
 'DISTRACTED BY OUTSIDE PERSON OBJECT OR EVENT' 'EATING OR DRINKING'
 'TALKING OR LISTENING TO CELLULAR PHONE' 'OTHER CELLULAR PHONE RELATED'
 'ADJUSTING AUDIO AND OR CLIMATE CONTROLS'
 'USING DEVICE OBJECT BROUGHT INTO VEHICLE' 'BY OTHER OCCUPANTS'
 'TEXTING FROM A CELLULAR PHONE' 'DIALING CELLULAR PHONE'
 'BY MOVING OBJECT IN VEHICLE' 'NO DRIVER PRESENT'
 'USING OTHER DEVICE CONTROLS INTEGRAL TO VEHICLE' 'SMOKING RELATED']


Drivers_License_State :
['MD' nan 'FL' 'AZ' 'DC' 'MO' 'DE' 'VA' 'NJ' 'WV' 'PA' 'IN' 'NC' 'MN'
 'MX-MEX' 'XX' 'TX' 'SC' 'CA' 'NY' 'US' 'GA' 'AL' 'WA' 'OH' 'CO' 'MA' 'CT'
 'NV' 'SD' 'ME' 'MS' 'MH' 'OR' 'AR' 'IL' 'KY' 'MI' 'NM' 'MP' 'KS' 'TN'
 'LA' 'NE' 'PR' 'VT' 'IA' 'MX-CMX' 'WY' 'UT' 'ID' 'MX-GRO' 'UM' 'HI'
 'CA-ON' 'CA-QC' 'MT' 'GU' 'MX-BCN' 'VI' 'WI' 'NH' 'OK' 'AK' 'MX-ROO' 'ON'
 'QC' 'MB' 'AB' 'ND' 'NF' 'IT' 'RI' 'NB' 'BC' 'NL' 'YT' 'FM' 'AS' 'SK'
 'NS' 'NT']


Vehicle_Damage :
['Disabling' 'Functional' 'Vehicle Not at Scene' 'Superficial' 'No Damage'
 nan 'DESTROYED']


Veh_1st_Impact_Loc :
['One O Clock' 'Six O Clock' 'Twelve O Clock' 'Two O Clock'
 'Vehicle Not at Scene' 'Eleven O Clock' 'Nine O Clock' 'Eight O Clock'
 'Seven O Clock' 'Five O Clock' 'Non-Collision' 'Ten O Clock'
 'Three O Clock' 'Four O Clock' 'Underside' 'Top' 'Cargo Loss'
 'EIGHT OCLOCK' 'SEVEN OCLOCK' 'TWELVE OCLOCK' nan 'ONE OCLOCK'
 'SIX OCLOCK' 'TEN OCLOCK' 'FOUR OCLOCK' 'TWO OCLOCK' 'ELEVEN OCLOCK'
 'THREE OCLOCK' 'NINE OCLOCK' 'FIVE OCLOCK' 'ROOF TOP']


Veh_Body_Type :
['Passenger Car' 'Sport Utility Vehicle' nan 'Single-Unit Truck'
 'Motorcycle - 2 Wheeled' 'Bus - School' 'Truck Tractor'
 'Van - Passenger (&lt;9 Seats)' 'Pickup' 'Station Wagon' 'Other Trucks'
 'Moped Or motorized bicycle' 'Bus - Transit' 'Van - Cargo'
 'Van - Passenger (9 or 12 Seats)' 'Bus - Mini' 'Low Speed Vehicle'
 'Autocycle' 'Golf Cart' 'All-Terrain Vehicle/All-Terrain Cycle (ATV/ATC)'
 'Bus - Other Type' 'Construction Equipment (backhoe, bulldozer, etc.)'
 'Snowmobile' 'Motor Home' 'Recreational Off-Highway Vehicles (ROV)'
 'Van - Passenger (15 Seats)'
 'Farm Equipment (Tractor, combine harvester, etc.)' 'Bus - Cross Country'
 'Motorcycle - 3 Wheeled' 'SCHOOL BUS' '(SPORT) UTILITY VEHICLE'
 'TRANSIT BUS' 'VAN' 'AMBULANCE/EMERGENCY' 'AMBULANCE/NON EMERGENCY'
 'PICKUP TRUCK' 'POLICE VEHICLE/EMERGENCY'
 'CARGO VAN/LIGHT TRUCK 2 AXLES (OVER 10,000LBS (4,536 KG))'
 'OTHER LIGHT TRUCKS (10,000LBS (4,536KG) OR LESS)'
 'FIRE VEHICLE/EMERGENCY' 'POLICE VEHICLE/NON EMERGENCY' 'MOPED'
 'FIRE VEHICLE/NON EMERGENCY' 'RECREATIONAL VEHICLE'
 'MEDIUM/HEAVY TRUCKS 3 AXLES (OVER 10,000LBS (4,536KG))' 'MOTORCYCLE'
 'ALL TERRAIN VEHICLE (ATV)' 'OTHER BUS' 'CROSS COUNTRY BUS'
 'FARM VEHICLE' 'LIMOUSINE']


Speed_Limit :
[40 35 25 45 30  0 15  5 55 50 20 10 60 75 65 70]


Parked_Vehicle :
['No' 'Yes' nan]


Vehicle_Year :
[2018. 2026. 2023. 2005. 2025. 2020.   nan 2009. 2011. 2024. 2016. 2014.
 2006. 2013. 2019. 2017. 2015. 2010. 2008. 2021. 2012. 2022. 1987. 1999.
 2003. 1998. 2001. 2004. 2002. 2007. 2000. 1992. 1983. 1966. 1997. 1996.
 1980. 1993. 1990. 1995. 1986. 1989. 1994. 1984. 1988. 1977. 1985. 1968.
 1991. 1967. 1957. 1978. 1981. 1938. 1982. 1974. 1961. 1976. 1969. 1930.
 1965. 1979. 1972. 1955. 1971. 1970. 1959. 1947. 1946. 1949. 1975. 1960.
 1963.]


Hit_Run :
['No' 'Yes' nan]


Lane_Type :
['Lane 2' 'Lane 1' nan 'Outside Right Of Way' 'Lane 1, Lane 2'
 'Lane 3, Lane 4' 'Lane 1, Parking Lot' 'Not Applicable, Parking Lot'
 'Lane 2, Other' 'Lane 1, Shoulder Area' 'Lane 3' 'Left Turn Lane'
 'Lane 1, Lane 3' 'Lane 2, Left Turn Lane' 'Shoulder Area'
 'Lane 4, Left Turn Lane' 'Lane 1, Other' 'Lane 1, Outside Right Of Way'
 'Lane 1, Left Turn Lane' 'Lane 1, Unknown' 'Lane 3, Unknown'
 'Lane 2, Parking Lot' 'Left Turn Lane, Median Area'
 'Left Turn Lane, Unknown' 'Right Turn Lane' 'Lane 2, Right Turn Lane'
 'Lane 3, Right Turn Lane' 'Lane 2, Shoulder Area' 'Lane 2, Lane 3'
 'Lane 1, Lane 2, Right Turn Lane' 'Off Road, Shoulder Area' 'Median Area'
 'Lane 1, Lane 3, Left Turn Lane' 'Lane 4' 'Lane 1, Off Road'
 'Crossover Area' 'Lane 3, Other' 'Not Applicable, Shoulder Area'
 'Lane 1, Lane 2, Left Turn Lane' 'Acceleration Lane'
 'Not Applicable, Other' 'Left Turn Lane, Right Turn Lane'
 'Lane 1, Not Applicable' 'Crossover Area, Lane 2, Lane 3'
 'Lane 1, Right Turn Lane' 'Lane 2, Outside Right Of Way'
 'Lane 3, Not Applicable' 'On Ramp' 'Lane 3, Left Turn Lane'
 'Left Turn Lane, Outside Right Of Way' 'Not Applicable, Unknown'
 'Crossover Area, Lane 2' 'Lane 1, Lane 2, Lane 3'
 'Acceleration Lane, Lane 2' 'Lane 1, Lane 3, Shoulder Area'
 'Crossover Area, Lane 1, Outside Right Of Way' 'Lane 5'
 'Lane 1, Median Area' 'Lane 1, Lane 2, Other'
 'Lane 1, Lane 2, Parking Lot' 'Lane 1, Left Turn Lane, Other'
 'Other, Parking Lot' 'Acceleration Lane, Left Turn Lane' 'Other, Unknown'
 'Lane 3, Shoulder Area' 'Other, Shoulder Area' 'Gore Area, Lane 1'
 'Crossover Area, Lane 4' 'Lane 1, Lane 4' 'Acceleration Lane, Lane 3'
 'Lane 1, Off Road, Shoulder Area' 'Lane 2, Median Area'
 'Lane 2, Left Turn Lane, Right Turn Lane' 'Crossover Area, Lane 1'
 'Lane 1, On Ramp' 'Lane 3, Median Area' 'Lane 2, Unknown'
 'Lane 1, Lane 5' 'Acceleration Lane, Lane 1, Left Turn Lane'
 'Parking Lot, Shoulder Area' 'Lane 2, Other, Separator' 'Lane 6'
 'Lane 2, Separator' 'Lane 2, Not Applicable' 'Lane 5, Lane 6'
 'Crossover Area, Left Turn Lane' 'Lane 2, Left Turn Lane, Parking Lot'
 'Crossover Area, Unknown' 'Lane 1, Lane 2, On Ramp'
 'Lane 4, Right Turn Lane' 'Crossover Area, Right Turn Lane'
 'Lane 2, On Ramp' 'Lane 3, Off Road' 'Lane 1, Lane 2, Shoulder Area'
 'Separator' 'Other, Right Turn Lane' 'Lane 3, Parking Lot'
 'Gore Area, Other' 'Crossover Area, Lane 3' 'Median Area, Other'
 'Lane 1, Lane 2, Median Area' 'Shoulder Area, Unknown' 'Lane 2, Off Road'
 'Gore Area, Shoulder Area' 'Lane 1, Separator' 'Lane 4, Other'
 'Other, Separator' 'Gore Area' 'Not Applicable, Off Road'
 'On Ramp, Right Turn Lane' 'Crossover Area, Lane 1, Off Road'
 'Median Area, Unknown' 'Off Road, Other' 'Lane 3, On Ramp'
 'Lane 4, Not Applicable' 'Left Turn Lane, Other'
 'Acceleration Lane, Lane 4' 'Lane 3, Left Turn Lane, Right Turn Lane'
 'Lane 4, On Ramp' 'Lane 1, Parking Lot, Shoulder Area' 'Lane 2, Lane 4'
 'Lane 1, Lane 2, Lane 3, Left Turn Lane' 'Crossover Area, Lane 1, Lane 2'
 'Acceleration Lane, Lane 1' 'Right Turn Lane, Unknown'
 'Deceleration Lane' 'Lane 2, Lane 3, Shoulder Area'
 'Crossover Area, Lane 1, Parking Lot' 'Lane 3, Outside Right Of Way'
 'Left Turn Lane, Shoulder Area' 'Lane 1, Other, Parking Lot'
 'Not Applicable, Right Turn Lane' 'Lane 2, Lane 3, Left Turn Lane'
 'Lane 2, Other, Unknown' 'Median Area, Shoulder Area'
 'Lane 1, Lane 2, Not Applicable' 'Lane 4, Lane 5'
 'Deceleration Lane, Lane 2' 'Not Applicable, Other, Parking Lot'
 'Parking Lot, Unknown' 'Lane 1, Lane 2, Lane 3, Parking Lot'
 'Lane 1, Median Area, Off Road' 'Crossover Area, Lane 3, Right Turn Lane'
 'Lane 1, Left Turn Lane, Right Turn Lane'
 'Lane 1, Lane 2, Lane 3, Left Turn Lane, Parking Lot'
 'Lane 1, Lane 2, Lane 4' 'Gore Area, Lane 3' 'Off Road' 'On Ramp, Other'
 'Left Turn Lane, Not Applicable' 'Gore Area, Lane 2' 'Lane 2, Lane 5'
 'Acceleration Lane, Other' 'Lane 1, Lane 2, Lane 3, Unknown'
 'Lane 1, Lane 4, Median Area' 'Lane 3, Lane 6' 'Lane 1, Lane 3, Other'
 'Lane 1, Lane 6' 'Lane 1, Lane 2, Lane 3, Not Applicable'
 'Crossover Area, Other' 'Acceleration Lane, Shoulder Area'
 'Outside Right Of Way, Shoulder Area' 'Crossover Area, On Ramp'
 'Crossover Area, Lane 1, Left Turn Lane'
 'Lane 1, Left Turn Lane, Unknown' 'Off Road, Unknown'
 'Crossover Area, Lane 3, Other'
 'Lane 1, Left Turn Lane, Not Applicable, Other'
 'Lane 1, Not Applicable, Other' 'Deceleration Lane, Outside Right Of Way'
 'Lane 3, Lane 5' 'Lane 2, Lane 3, Right Turn Lane' 'On Ramp, Unknown'
 'Lane 1, Lane 3, Right Turn Lane' 'Not Applicable, Outside Right Of Way'
 'Lane 4, Off Road' 'Lane 1, Lane 2, Outside Right Of Way'
 'Lane 1, Off Road, Other' 'Lane 1, Outside Right Of Way, Shoulder Area'
 'Off Road, Outside Right Of Way, Shoulder Area' 'Lane 5, Shoulder Area'
 'Left Turn Lane, Off Road' 'Other, Outside Right Of Way'
 'Deceleration Lane, Lane 4' 'Lane 3, Separator'
 'Lane 1, Lane 2, Left Turn Lane, Median Area'
 'Lane 2, Median Area, Off Road' 'Lane 1, Other, Outside Right Of Way'
 'Lane 2, Not Applicable, Other' 'Crossover Area, Median Area'
 'Lane 2, Lane 3, Lane 4' 'Lane 5, Right Turn Lane'
 'Lane 1, Other, Shoulder Area' 'Lane 3, Median Area, Other'
 'Lane 2, Lane 3, Unknown' 'Lane 3, Lane 4, Unknown' 'Parking Lot'
 'Not Applicable, Other, Unknown']


At Fault :
['DRIVER' nan 'NONMOTORIST' 'BOTH']


First_Harmful_Event :
['Motor Vehicle In Transport' 'Pedalcycle' 'Pedestrian' 'Fence'
 'Parked Vehicle' 'Curb' 'Tree (standing)' 'Other Post, Pole, Or Support'
 'Guardrail Face' 'Utility Pole/Light Support' 'Concrete Traffic Barrier'
 'Traffic Sign Support'
 'Other Fixed Object (wall, building, tunnel, etc.)'
 'Other Non-Fixed Object' 'Animal (live)' 'Other Non-Motorist'
 'Traffic Signal Support' 'Mailbox' 'Other Traffic Barrier' 'Ditch' nan
 'Overturn/Rollover' 'Fell Jumped from Motor Vehicle'
 'Other Non-Collision' 'Bridge Pier Or Support' 'Embankment'
 'Cable Barrier' 'Guardrail End Terminal'
 'Railway Vehicle (train, engine)' 'Culvert' 'Thrown Or Falling Object'
 'Bridge Rail' 'Explosion Or Fire' 'Spilled Cargo'
 'Strikes Object at Rest from Motor Vehicle In Transport'
 'Struck by Falling, Shifting Cargo Or Anything Set In Motion by Motor Vehicle'
 'Construction Equipment' 'Impact Attenuator/Crash Cushion'
 'Bridge Overhead Structure' 'Units Separated'
 'Cargo/Equipment Loss Or Shift' 'Jackknife' 'OTHER VEHICLE' 'OFF ROAD'
 'FIXED OBJECT' 'OTHER OBJECT' 'ANIMAL' 'BICYCLE' 'OVERTURN' 'BACKING'
 'OTHER NON COLLISION' 'OTHER CONVEYANCE' 'RAILWAY TRAIN'
 'OTHER PEDALCYCLE' 'U-TURN' 'DOWNHILL RUNAWAY' 'IMMERSION']


Junction :
['Non-Junction' 'Acceleration/Deceleration Lane' 'Crossover-Related'
 'Intersection or Related' 'Entrance/Exit Ramp or Related' nan
 'Through Roadway' 'Driveway Access or Related'
 'Other Location Not Listed Above Within an Interchange Area (median,\nshoulder and roadside)'
 'Shared-Use Path or Trail' 'Railway Grade Crossing' 'INTERSECTION'
 'NON INTERSECTION' 'INTERSECTION RELATED' 'OTHER DRIVEWAY'
 'INTERCHANGE RELATED' 'COMMERCIAL DRIVEWAY' 'CROSSOVER RELATED'
 'RESIDENTIAL DRIVEWAY' 'ALLEY']


Intersection_Type :
[nan 'Perpendicular' 'Angled/Skewed' 'Roundabout/Traffic Circle'
 'FOUR-WAY INTERSECTION' 'T-INTERSECTION' 'FIVE-POINT OR MORE'
 'Y-INTERSECTION' 'ROUNDABOUT' 'TRAFFIC CIRCLE']


Road Alignment :
['Straight' nan 'Curve Left' 'Curve Left, Straight' 'Curve Right'
 'Curve Left, Curve Right' 'Curve Right, Straight'
 'Curve Left, Curve Right, Straight']


Road_Condition :
['No Defects' nan 'Holes Ruts Etc' 'Foreign Material'
 'Loose Surface Material' 'View Obstructed' 'Obstruction Not Signaled'
 'Shoulder Defect' 'Obstruction Not Lighted']

In [30]:
# Clean "Drivers_License_State"

# Replace "XX" with nan
crash_culled_df["Drivers_License_State"] = crash_culled_df["Drivers_License_State"].replace("XX", np.nan)

# Replace specific Mexican codes with "Mex"
mexican_codes = ["MX-MEX", "MX-ROO", "MX-GRO", "MX-BCN", "MX-CMX"]
crash_culled_df['Drivers_License_State'] = crash_culled_df["Drivers_License_State"].replace(mexican_codes, "Mex")

# Replace Canadian province codes with "Can"
canadian_codes_pattern = r"^(CA-ON|CA-QC|ON|QC|BC|AB|MB|NB|NL|NS|NT|NU|PE|SK|YT)$"
crash_culled_df['Drivers_License_State'] = crash_culled_df["Drivers_License_State"].replace(
    canadian_codes_pattern, "Can", regex=True)

# Standardize US territories to "US-Territory"
us_territories = ["PR", "GU", "VI", "AS", "MP", "UM"]
crash_culled_df["Drivers_License_State"] = crash_culled_df["Drivers_License_State"].replace(us_territories, "US-Territory")

# Standardize other foreign or generic codes to "Foreign/Other"
foreign_other_codes = ["US", "MH", "FM", "NF", "IT"]
crash_culled_df["Drivers_License_State"] = crash_culled_df["Drivers_License_State"].replace(foreign_other_codes, "Foreign/Other")

# print("Unique values after cleaning Drivers_License_State:")
# print(crash_culled_df["Drivers_License_State"].unique())
# print("\nValue counts for Drivers_License_State:")
# print(crash_culled_df["Drivers_License_State"].value_counts(dropna=False))

In [11]:
us_states_dc = {
    "AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "ID",
    "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI",
    "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
    "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN",
    "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY", "AK", "HI",
    "DC"
}

In [12]:
unique_states = crash_culled_df["Drivers_License_State"].unique()
print(unique_states)
crash_culled_df["Drivers_License_State"].nunique()

['MD' nan 'FL' 'AZ' 'DC' 'MO' 'DE' 'VA' 'NJ' 'WV' 'PA' 'IN' 'NC' 'MN'
 'Mex' 'TX' 'SC' 'CA' 'NY' 'Foreign/Other' 'GA' 'AL' 'WA' 'OH' 'CO' 'MA'
 'CT' 'NV' 'SD' 'ME' 'MS' 'OR' 'AR' 'IL' 'KY' 'MI' 'NM' 'US-Territory'
 'KS' 'TN' 'LA' 'NE' 'VT' 'IA' 'WY' 'UT' 'ID' 'HI' 'Can' 'MT' 'WI' 'NH'
 'OK' 'AK' 'ND' 'RI']

55

In [13]:

# Filter out contiguous US states from the unique driver's license states
non_us_states = [state for state in unique_states if state not in us_states_dc and pd.notna(state)]

print("Driver's License States not in contiguous US states (or already standardized):")
print(non_us_states)

Driver's License States not in contiguous US states (or already standardized):
['Mex', 'Foreign/Other', 'US-Territory', 'Can']

In [14]:
print("Unique values after cleaning Drivers_License_State:")
print(crash_culled_df["Drivers_License_State"].unique())
print("\nValue counts for Drivers_License_State:")
print(crash_culled_df["Drivers_License_State"].value_counts(dropna=False))
print("\nNumber of unique:")
print(crash_culled_df["Drivers_License_State"].nunique())

Unique values after cleaning Drivers_License_State:
['MD' nan 'FL' 'AZ' 'DC' 'MO' 'DE' 'VA' 'NJ' 'WV' 'PA' 'IN' 'NC' 'MN'
 'Mex' 'TX' 'SC' 'CA' 'NY' 'Foreign/Other' 'GA' 'AL' 'WA' 'OH' 'CO' 'MA'
 'CT' 'NV' 'SD' 'ME' 'MS' 'OR' 'AR' 'IL' 'KY' 'MI' 'NM' 'US-Territory'
 'KS' 'TN' 'LA' 'NE' 'VT' 'IA' 'WY' 'UT' 'ID' 'HI' 'Can' 'MT' 'WI' 'NH'
 'OK' 'AK' 'ND' 'RI']

Value counts for Drivers_License_State:
Drivers_License_State
MD               176529
NaN               16637
DC                 6197
VA                 6099
PA                 1318
FL                  930
NY                  648
WV                  557
NC                  485
MA                  468
NJ                  448
CA                  419
TX                  412
Foreign/Other       324
GA                  314
DE                  236
OH                  208
SC                  173
WA                  158
IL                  133
Can                 128
MI                  113
TN                  111
CT                  104
CO                   96
ME                   95
AZ                   92
IN                   75
AL                   73
LA                   67
MO                   48
MN                   43
US-Territory         40
WI                   37
MS                   36
UT                   33
NV                   30
NM                   30
ND                   29
OR                   29
KY                   29
AR                   25
OK                   25
AK                   23
HI                   21
IA                   20
KS                   19
VT                   18
NH                   17
NE                   17
ID                   16
RI                   11
WY                    9
Mex                   8
MT                    7
SD                    6
Name: count, dtype: int64

Number of unique:
55

---------
Clean Intersection_Type
--------------

In [15]:
# Clean Intersection_Type (as generated in previous turn)
crash_culled_df["Intersection_Type"] = crash_culled_df["Intersection_Type"].replace(
    ["ROUNDABOUT", "TRAFFIC CIRCLE"], "Roundabout/Traffic Circle"
)

print("Unique values after cleaning Intersection_Type:")
print(crash_culled_df["Intersection_Type"].unique())

# Transform Lane_Type to Parking_Lot_YN (Y/N/nan)
# Create a temporary series for the new values based on Lane_Type
new_parking_lot_yn_values = crash_culled_df["Lane_Type"].astype(str).str.contains("parking lot", case=False, na=False).map({True: "Y", False: "N"})

# Set to NaN where original Lane_Type was NaN
new_parking_lot_yn_values = new_parking_lot_yn_values.mask(crash_culled_df["Lane_Type"].isna(), np.nan)

# Apply the 'check against off road' condition
# If First_Harmful_Event is 'OFF ROAD' (case-insensitive), then it's not a parking lot, set to 'N'
off_road_condition = crash_culled_df["First_Harmful_Event"].astype(str).str.contains("off road", case=False, na=False)
new_parking_lot_yn_values.loc[off_road_condition] = "N"

# Replace the original 'Lane_Type' column with the new values
crash_culled_df["Lane_Type"] = new_parking_lot_yn_values

# Rename the column to reflect its new meaning
crash_culled_df.rename(columns={"Lane_Type": "Parking_Lot_YN"}, inplace=True)

# Display unique values and value counts for the transformed column
print("\nUnique values of transformed \"Parking_Lot_YN\" column:")
print(crash_culled_df["Parking_Lot_YN"].unique())
print("\nValue counts for \"Parking_Lot_YN\" column:")
print(crash_culled_df["Parking_Lot_YN"].value_counts(dropna=False))

Unique values after cleaning Intersection_Type:
[nan 'Perpendicular' 'Angled/Skewed' 'Roundabout/Traffic Circle'
 'FOUR-WAY INTERSECTION' 'T-INTERSECTION' 'FIVE-POINT OR MORE'
 'Y-INTERSECTION']

Unique values of transformed "Parking_Lot_YN" column:
['N' nan 'Y']

Value counts for "Parking_Lot_YN" column:
Parking_Lot_YN
NaN    162000
N       52108
Y         165
Name: count, dtype: int64

Parking_Lot_YN   
  Since the proportion of entries with "Y" or "N" values is so low compared to NaN,  
  this variable cannot be used for meaningful analysis at this time.

In [16]:
print(crash_culled_df["Intersection_Type"].unique())

[nan 'Perpendicular' 'Angled/Skewed' 'Roundabout/Traffic Circle'
 'FOUR-WAY INTERSECTION' 'T-INTERSECTION' 'FIVE-POINT OR MORE'
 'Y-INTERSECTION']

In [17]:
# Clean Vehicle_Damage: caseblind, "unkonwn" = "other" = nan
# Convert to string and uppercase to handle case-insensitivity
crash_culled_df["Vehicle_Damage"] = crash_culled_df["Vehicle_Damage"].astype(str).str.upper()

# Define values to replace (now all in uppercase)
values_to_replace_vd = ["UNKONWN", "OTHER", "UNKNOWN", "NAN", "NA"]

# Replace these values with np.nan
crash_culled_df["Vehicle_Damage"] = crash_culled_df["Vehicle_Damage"].replace(values_to_replace_vd, np.nan)

print("Unique values after cleaning Vehicle_Damage:")
print(crash_culled_df["Vehicle_Damage"].unique())
print("\nValue counts for Vehicle_Damage:")
print(crash_culled_df["Vehicle_Damage"].value_counts(dropna=False))

Unique values after cleaning Vehicle_Damage:
['DISABLING' 'FUNCTIONAL' 'VEHICLE NOT AT SCENE' 'SUPERFICIAL' 'NO DAMAGE'
 nan 'DESTROYED']

Value counts for Vehicle_Damage:
Vehicle_Damage
DISABLING               79964
SUPERFICIAL             55186
FUNCTIONAL              54644
DESTROYED                7610
NaN                      7038
NO DAMAGE                6691
VEHICLE NOT AT SCENE     3140
Name: count, dtype: int64

In [18]:
# Clean Veh_1st_Impact_Loc: "ROOF TOP" = "roof" = "top"; caseblind; OCLOCK = O Clock to O"Clock

# Convert to string and uppercase for case-insensitivity
crash_culled_df["Veh_1st_Impact_Loc"] = crash_culled_df["Veh_1st_Impact_Loc"].astype(str).str.upper()

# Standardize "ROOF TOP", "ROOF", "TOP" to "ROOF TOP"
crash_culled_df["Veh_1st_Impact_Loc"] = crash_culled_df["Veh_1st_Impact_Loc"].replace(
    r"^(ROOF TOP|ROOF|Top)$", "TOP", regex=True
)

# Create a mapping for clock-related terms to standardize them to O"CLOCK format
clock_mapping = {
    "ONE O CLOCK": "ONE O\'CLOCK", "SIX O CLOCK": "SIX O\'CLOCK", "TWELVE O CLOCK": "TWELVE O\'CLOCK",
    "TWO O CLOCK": "TWO O\'CLOCK", "ELEVEN O CLOCK": "ELEVEN O\'CLOCK", "NINE O CLOCK": "NINE O\'CLOCK",
    "EIGHT O CLOCK": "EIGHT O\'CLOCK", "SEVEN O CLOCK": "SEVEN O\'CLOCK", "FIVE O CLOCK": "FIVE O\'CLOCK",
    "TEN O CLOCK": "TEN O\'CLOCK", "THREE O CLOCK": "THREE O\'CLOCK", "FOUR O CLOCK": "FOUR O\'CLOCK",
    "ONE OCLOCK": "ONE O\'CLOCK", "SIX OCLOCK": "SIX O\'CLOCK", "TWELVE OCLOCK": "TWELVE O\'CLOCK",
    "TWO OCLOCK": "TWO O\'CLOCK", "ELEVEN OCLOCK": "ELEVEN O\'CLOCK", "NINE OCLOCK": "NINE O\'CLOCK",
    "EIGHT OCLOCK": "EIGHT O\'CLOCK", "SEVEN OCLOCK": "SEVEN O\'CLOCK", "FIVE OCLOCK": "FIVE O\'CLOCK",
    "TEN OCLOCK": "TEN O\'CLOCK", "THREE OCLOCK": "THREE O\'CLOCK", "FOUR OCLOCK": "FOUR O\'CLOCK",
    "OCLOCK": "O\'CLOCK", "O CLOCK": "O\'CLOCK"
}
crash_culled_df["Veh_1st_Impact_Loc"] = crash_culled_df["Veh_1st_Impact_Loc"].replace(clock_mapping)

# Replace "NAN" string with np.nan
crash_culled_df["Veh_1st_Impact_Loc"] = crash_culled_df["Veh_1st_Impact_Loc"].replace("NAN", np.nan)

print("Unique values after cleaning Veh_1st_Impact_Loc:")
print(crash_culled_df["Veh_1st_Impact_Loc"].unique())
print("\nValue counts for Veh_1st_Impact_Loc:")
print(crash_culled_df["Veh_1st_Impact_Loc"].value_counts(dropna=False))

Unique values after cleaning Veh_1st_Impact_Loc:
["ONE O'CLOCK" "SIX O'CLOCK" "TWELVE O'CLOCK" "TWO O'CLOCK"
 'VEHICLE NOT AT SCENE' "ELEVEN O'CLOCK" "NINE O'CLOCK" "EIGHT O'CLOCK"
 "SEVEN O'CLOCK" "FIVE O'CLOCK" 'NON-COLLISION' "TEN O'CLOCK"
 "THREE O'CLOCK" "FOUR O'CLOCK" 'UNDERSIDE' 'TOP' 'CARGO LOSS' nan]

Value counts for Veh_1st_Impact_Loc:
Veh_1st_Impact_Loc
TWELVE O'CLOCK          80299
SIX O'CLOCK             40093
ONE O'CLOCK             20725
ELEVEN O'CLOCK          18142
TEN O'CLOCK              7985
TWO O'CLOCK              7881
SEVEN O'CLOCK            5802
FIVE O'CLOCK             5391
FOUR O'CLOCK             5220
THREE O'CLOCK            4755
EIGHT O'CLOCK            4708
NINE O'CLOCK             4702
NaN                      3238
VEHICLE NOT AT SCENE     3140
NON-COLLISION             841
UNDERSIDE                 711
TOP                       599
CARGO LOSS                 41
Name: count, dtype: int64

####Clock Positions and Crash Impact
Twelve o'clock = front bumper  
Three  o'clock = right (US passenger) side center  
Six o'clock = rear bumper  
Nine o'clock = left (US driver) side center  

Alaska Department of Public Safety  
https://tracs.dps.alaska.gov/TechSupport/12-200.1/MotorVehicle/DamagedAreas.htm

In [19]:
# Clean Driver_Distraction: Unknown = UNKNOWN = "NO DRIVER PRESENT" = nan
# Convert to string and uppercase to handle case-insensitivity
crash_culled_df["Driver_Distraction"] = crash_culled_df["Driver_Distraction"].astype(str).str.upper()

# Define values to replace (now all in uppercase)
values_to_replace_dd = ["UNKNOWN", "NO DRIVER PRESENT", "NAN", "NA"]

# Replace these values with np.nan
crash_culled_df["Driver_Distraction"] = crash_culled_df["Driver_Distraction"].replace(values_to_replace_dd, np.nan)

# Ensure any remaining 'nan' string (which might come from initial NaN conversion to string) is np.nan
crash_culled_df["Driver_Distraction"] = crash_culled_df["Driver_Distraction"].replace("NAN", np.nan)

print("Unique values after cleaning Driver_Distraction:")
print(crash_culled_df["Driver_Distraction"].unique())
print("\nValue counts for Driver_Distraction:")
print(crash_culled_df["Driver_Distraction"].value_counts(dropna=False))

Unique values after cleaning Driver_Distraction:
['NOT DISTRACTED' nan 'TALKING/LISTENING'
 'OTHER ACTION (LOOKING AWAY FROM TASK, ETC.)'
 'MANUALLY OPERATING (DIALING, PLAYING GAME, ETC.)'
 'LOOKED BUT DID NOT SEE' 'OTHER DISTRACTION'
 'OTHER ELECTRONIC DEVICE (NAVIGATIONAL PALM PILOT)'
 'INATTENTIVE OR LOST IN THOUGHT'
 'DISTRACTED BY OUTSIDE PERSON OBJECT OR EVENT' 'EATING OR DRINKING'
 'TALKING OR LISTENING TO CELLULAR PHONE' 'OTHER CELLULAR PHONE RELATED'
 'ADJUSTING AUDIO AND OR CLIMATE CONTROLS'
 'USING DEVICE OBJECT BROUGHT INTO VEHICLE' 'BY OTHER OCCUPANTS'
 'TEXTING FROM A CELLULAR PHONE' 'DIALING CELLULAR PHONE'
 'BY MOVING OBJECT IN VEHICLE'
 'USING OTHER DEVICE CONTROLS INTEGRAL TO VEHICLE' 'SMOKING RELATED']

Value counts for Driver_Distraction:
Driver_Distraction
NOT DISTRACTED                                       134589
NaN                                                   46101
LOOKED BUT DID NOT SEE                                21546
INATTENTIVE OR LOST IN THOUGHT                         4320
OTHER DISTRACTION                                      3245
OTHER ACTION (LOOKING AWAY FROM TASK, ETC.)            1119
DISTRACTED BY OUTSIDE PERSON OBJECT OR EVENT            970
BY OTHER OCCUPANTS                                      418
OTHER CELLULAR PHONE RELATED                            372
OTHER ELECTRONIC DEVICE (NAVIGATIONAL PALM PILOT)       325
TALKING OR LISTENING TO CELLULAR PHONE                  282
BY MOVING OBJECT IN VEHICLE                             212
EATING OR DRINKING                                      196
ADJUSTING AUDIO AND OR CLIMATE CONTROLS                 134
TALKING/LISTENING                                        97
USING OTHER DEVICE CONTROLS INTEGRAL TO VEHICLE          92
TEXTING FROM A CELLULAR PHONE                            67
USING DEVICE OBJECT BROUGHT INTO VEHICLE                 63
MANUALLY OPERATING (DIALING, PLAYING GAME, ETC.)         51
DIALING CELLULAR PHONE                                   48
SMOKING RELATED                                          26
Name: count, dtype: int64

------
####Driver_Distraction  

these categories are good.  
Optional to later group into  
Device-related,  
Passenger-related  
Vehicle device controls  
etc.

In [20]:
# Clean Collision_Type: 'other' = 'unknown' = nan
values_to_replace_ct = ["other", "unknown", "OTHER", "UNKNOWN"]
crash_culled_df["Collision_Type"] = crash_culled_df["Collision_Type"].astype(str).replace(values_to_replace_ct, np.nan, regex=True)

print("Unique values after cleaning Collision_Type:")
print(crash_culled_df["Collision_Type"].unique())
print("\nValue counts for Collision_Type:")
print(crash_culled_df["Collision_Type"].value_counts(dropna=False))

Unique values after cleaning Collision_Type:
['Front to Front' 'Front to Rear' 'Angle' 'Single Vehicle'
 'Sideswipe, Opposite Direction' 'nan' 'Rear To Side' 'Rear To Rear'
 'Sideswipe, Same Direction' 'OPPOSITE DIRECTION SIDESWIPE'
 'HEAD ON LEFT TURN' 'STRAIGHT MOVEMENT ANGLE' 'SAME DIR REAR END'
 'HEAD ON' 'SAME DIRECTION SIDESWIPE' 'SAME DIRECTION RIGHT TURN'
 'SAME DIRECTION LEFT TURN' 'ANGLE MEETS LEFT TURN'
 'SAME DIR BOTH LEFT TURN' 'SAME DIR REND LEFT TURN'
 'ANGLE MEETS RIGHT TURN' 'OPPOSITE DIR BOTH LEFT TURN'
 'ANGLE MEETS LEFT HEAD ON' 'SAME DIR REND RIGHT TURN']

Value counts for Collision_Type:
Collision_Type
SAME DIR REAR END                55759
STRAIGHT MOVEMENT ANGLE          30342
nan                              23111
Single Vehicle                   20818
SAME DIRECTION SIDESWIPE         16227
HEAD ON LEFT TURN                12926
Front to Rear                    12494
Angle                             8897
Sideswipe, Same Direction         6706
SAME DIRECTION RIGHT TURN         3832
HEAD ON                           3786
SAME DIRECTION LEFT TURN          3715
OPPOSITE DIRECTION SIDESWIPE      2883
Front to Front                    2352
ANGLE MEETS LEFT TURN             2033
Rear To Side                      1909
Sideswipe, Opposite Direction     1570
ANGLE MEETS RIGHT TURN            1204
SAME DIR REND LEFT TURN            743
SAME DIR REND RIGHT TURN           720
SAME DIR BOTH LEFT TURN            719
ANGLE MEETS LEFT HEAD ON           700
Rear To Rear                       505
OPPOSITE DIR BOTH LEFT TURN        322
Name: count, dtype: int64

####Collision_Type
Don't use for now:  too many groups

-----------------
####Veh_Body_Type
Part I.

In [40]:
# Clean Veh_Body_Type: caseblind, unknown = other = nan
# Convert to uppercase for case-insensitivity, then replace 'UNKNOWN' and 'OTHER' with NaN
crash_culled_df["Veh_Body_Type"] = crash_culled_df["Veh_Body_Type"].astype(str).str.upper()
values_to_replace_vbt = ["UNKNOWN", "OTHER", "NAN"]
crash_culled_df["Veh_Body_Type"] = crash_culled_df["Veh_Body_Type"].replace(values_to_replace_vbt, np.nan)

print("Unique values after cleaning Veh_Body_Type:")
print(crash_culled_df["Veh_Body_Type"].unique())
print("\nValue counts for Veh_Body_Type:")
print(crash_culled_df["Veh_Body_Type"].value_counts(dropna=False))
print("\nTotal count:")
print(crash_culled_df["Veh_Body_Type"].nunique())

Unique values after cleaning Veh_Body_Type:
['PASSENGER CAR' 'SPORT UTILITY VEHICLE' nan 'SINGLE-UNIT TRUCK'
 'MOTORCYCLE - 2 WHEELED' 'BUS - SCHOOL' 'TRUCK TRACTOR'
 'VAN - PASSENGER (&LT;9 SEATS)' 'PICKUP' 'STATION WAGON' 'OTHER TRUCKS'
 'MOPED OR MOTORIZED BICYCLE' 'BUS - TRANSIT' 'VAN - CARGO'
 'VAN - PASSENGER (9 OR 12 SEATS)' 'BUS - MINI' 'LOW SPEED VEHICLE'
 'AUTOCYCLE' 'GOLF CART' 'ALL-TERRAIN VEHICLE/ALL-TERRAIN CYCLE (ATV/ATC)'
 'BUS - OTHER TYPE' 'CONSTRUCTION EQUIPMENT (BACKHOE, BULLDOZER, ETC.)'
 'SNOWMOBILE' 'MOTOR HOME' 'RECREATIONAL OFF-HIGHWAY VEHICLES (ROV)'
 'VAN - PASSENGER (15 SEATS)'
 'FARM EQUIPMENT (TRACTOR, COMBINE HARVESTER, ETC.)' 'BUS - CROSS COUNTRY'
 'MOTORCYCLE - 3 WHEELED' 'SCHOOL BUS' '(SPORT) UTILITY VEHICLE'
 'TRANSIT BUS' 'VAN' 'AMBULANCE/EMERGENCY' 'AMBULANCE/NON EMERGENCY'
 'PICKUP TRUCK' 'POLICE VEHICLE/EMERGENCY'
 'CARGO VAN/LIGHT TRUCK 2 AXLES (OVER 10,000LBS (4,536 KG))'
 'OTHER LIGHT TRUCKS (10,000LBS (4,536KG) OR LESS)'
 'FIRE VEHICLE/EMERGENCY' 'POLICE VEHICLE/NON EMERGENCY' 'MOPED'
 'FIRE VEHICLE/NON EMERGENCY' 'RECREATIONAL VEHICLE'
 'MEDIUM/HEAVY TRUCKS 3 AXLES (OVER 10,000LBS (4,536KG))' 'MOTORCYCLE'
 'ALL TERRAIN VEHICLE (ATV)' 'OTHER BUS' 'CROSS COUNTRY BUS'
 'FARM VEHICLE' 'LIMOUSINE']

Value counts for Veh_Body_Type:
Veh_Body_Type
PASSENGER CAR                                                146298
(SPORT) UTILITY VEHICLE                                       15990
PICKUP TRUCK                                                   6787
SPORT UTILITY VEHICLE                                          6693
NaN                                                            6428
VAN                                                            4958
TRANSIT BUS                                                    3642
SCHOOL BUS                                                     2975
PICKUP                                                         2139
POLICE VEHICLE/NON EMERGENCY                                   2119
OTHER LIGHT TRUCKS (10,000LBS (4,536KG) OR LESS)               1909
CARGO VAN/LIGHT TRUCK 2 AXLES (OVER 10,000LBS (4,536 KG))      1858
POLICE VEHICLE/EMERGENCY                                       1497
MEDIUM/HEAVY TRUCKS 3 AXLES (OVER 10,000LBS (4,536KG))         1469
BUS - TRANSIT                                                  1069
BUS - SCHOOL                                                    985
STATION WAGON                                                   949
VAN - PASSENGER (&LT;9 SEATS)                                   935
MOTORCYCLE                                                      889
TRUCK TRACTOR                                                   645
OTHER TRUCKS                                                    538
AMBULANCE/EMERGENCY                                             466
FIRE VEHICLE/EMERGENCY                                          437
OTHER BUS                                                       418
SINGLE-UNIT TRUCK                                               338
FIRE VEHICLE/NON EMERGENCY                                      296
VAN - CARGO                                                     242
MOTORCYCLE - 2 WHEELED                                          214
RECREATIONAL VEHICLE                                            197
AMBULANCE/NON EMERGENCY                                         185
SNOWMOBILE                                                      130
ALL TERRAIN VEHICLE (ATV)                                       119
MOPED                                                            87
MOPED OR MOTORIZED BICYCLE                                       57
AUTOCYCLE                                                        50
ALL-TERRAIN VEHICLE/ALL-TERRAIN CYCLE (ATV/ATC)                  45
LOW SPEED VEHICLE                                                40
BUS - OTHER TYPE                                                 36
CROSS COUNTRY BUS                                                31
CONSTRUCTION EQUIPMENT (BACKHOE, BULLDOZER, ETC.)                25
FARM VEHICLE                                                     21
BUS - MINI                                                       20
LIMOUSINE                                                        16
VAN - PASSENGER (9 OR 12 SEATS)                                   8
RECREATIONAL OFF-HIGHWAY VEHICLES (ROV)                           7
GOLF CART                                                         3
VAN - PASSENGER (15 SEATS)                                        3
FARM EQUIPMENT (TRACTOR, COMBINE HARVESTER, ETC.)                 3
MOTORCYCLE - 3 WHEELED                                            3
BUS - CROSS COUNTRY                                               3
MOTOR HOME                                                        1
Name: count, dtype: int64

Total count:
50

In [56]:
# Correct column name mistake, insert underscores


crash_culled_df = crash_culled_df.rename(columns={
    "Road Alignment" : "Road_Alignment",
    "At Fault" : "At_Fault"
})

print("Columns after renaming:")
print(crash_culled_df.columns)

Columns after renaming:
Index(['Vehicle_Num', 'Agency_Name', 'ACRS_Report_Type', 'Crash_Date_Time',
       'Related_Non_Motorist', 'Collision_Type', 'Weather',
       'Surface_Condition', 'Ambient_Light', 'Traffic_Control',
       'Driver_Substance_Use', 'Non_Motorist_Substance_Use', 'Driver_At_Fault',
       'Injury_Severity', 'Driver_Distraction', 'Drivers_License_State',
       'Vehicle_Damage', 'Veh_1st_Impact_Loc', 'Veh_Body_Type', 'Speed_Limit',
       'Parked_Vehicle', 'Vehicle_Year', 'Hit_Run', 'Lane_Type', 'At_Fault',
       'First_Harmful_Event', 'Junction', 'Intersection_Type',
       'Road_Alignment', 'Road_Condition'],
      dtype='object')

-----------------
####Veh_Body_Type
Part II.   Continue grouping redundancies

In [42]:
# list of remaining desired variables
column_list_culled_2 = ["Vehicle_Num", "Agency_Name", "ACRS_Report_Type", "Crash_Date_Time", "Related_Non_Motorist", "Weather", "Surface_Condition", "Ambient_Light", "Traffic_Control", "Driver_Substance_Use", "Non_Motorist_Substance_Use", "Driver_At_Fault", "Injury_Severity", "Driver_Distraction", "Drivers_License_State", "Vehicle_Damage", "Veh_1st_Impact_Loc", "Veh_Body_Type", "Speed_Limit", "Parked_Vehicle", "Vehicle_Year", "Hit_Run", "At Fault", "First_Harmful_Event", "Junction", "Intersection_Type", "Road Alignment", "Road_Condition"]

# Create new df with fewer but larger groups
crash_grouped_df = crash_culled_df[column_list_culled_2].copy()

In [45]:
crash_grouped_df["Veh_Body_Type"] = crash_grouped_df["Veh_Body_Type"].replace({
    "NAN" : np.nan,
    "CROSS COUNTRY BUS" : "BUS - CROSS COUNTRY (Coach)",
    "ALL TERRAIN VEHICLE (ATV)" :  "ALL TERRAIN VEHICLE (ATV/ATC)",
    "ALL-TERRAIN VEHICLE/ALL-TERRAIN CYCLE (ATV/ATC)" :  "ALL TERRAIN VEHICLE (ATV/ATC)",
    "TRANSIT BUS" : "BUS - TRANSIT",
    "MOPED" : "MOPED OR MOTORIZED BICYCLE",
    "SCHOOL BUS" : "BUS - SCHOOL",
    "(SPORT) UTILITY VEHICLE": "SPORT UTILITY VEHICLE (SUV)",
    "SPORT UTILITY VEHICLE": "SPORT UTILITY VEHICLE (SUV)",
    "PICKUP" : "PICKUP TRUCK",
    "MOTORCYCLE" : "MOTORCYCLE - 2 WHEELED",
    "MOTOR HOME" : "RECREATIONAL VEHICLE",
    "MOTORCYCLE - 3 WHEELED": "OTHER",
    "LIMOUSINE": "OTHER",
    "LOW SPEED VEHICLE": "OTHER",
    "GOLF CART": "OTHER",
    "AUTOCYCLE": "OTHER",
    "RECREATIONAL OFF-HIGHWAY VEHICLES (ROV)": "OTHER",
    "FARM EQUIPMENT (TRACTOR, COMBINE HARVESTER, ETC.)": "OTHER",
    "FARM VEHICLE": "OTHER",
    "CONSTRUCTION EQUIPMENT (BACKHOE, BULLDOZER, ETC.)": "OTHER",
    "SNOWMOBILE": "OTHER",
    "STATION WAGON" : "PASSENGER CAR",
    "VAN - PASSENGER (&LT;9 SEATS)": "VAN - PASSENGER",
    "VAN - PASSENGER (15 SEATS)": "VAN - PASSENGER",
    "VAN - PASSENGER (9 OR 12 SEATS)": "VAN - PASSENGER",
    "BUS - MINI": "VAN - PASSENGER",
    "VAN" : "VAN - PASSENGER",
    "VAN - CARGO": "VAN - CARGO/LIGHT TRUCK 2 AXLES",
    "CARGO VAN/LIGHT TRUCK 2 AXLES (OVER 10,000LBS (4,536 KG))" : "VAN - CARGO/LIGHT TRUCK 2 AXLES",
    "MEDIUM/HEAVY TRUCKS 3 AXLES (OVER 10,000LBS (4,536KG))" : "MEDIUM/HEAVY TRUCKS 3 AXLES",
    "SINGLE-UNIT TRUCK" : "SINGLE-UNIT TRUCK (BOX)"
})

print("\nValue counts for")
print(crash_grouped_df["Veh_Body_Type"].value_counts(dropna=False).sort_index())
print("\nTotal number of groups:")
print(crash_grouped_df["Veh_Body_Type"].nunique())

Value counts for
Veh_Body_Type
ALL TERRAIN VEHICLE (ATV/ATC)                          164
AMBULANCE/EMERGENCY                                    466
AMBULANCE/NON EMERGENCY                                185
BUS - CROSS COUNTRY                                      3
BUS - CROSS COUNTRY (Coach)                             31
BUS - OTHER TYPE                                        36
BUS - SCHOOL                                          3960
BUS - TRANSIT                                         4711
FIRE VEHICLE/EMERGENCY                                 437
FIRE VEHICLE/NON EMERGENCY                             296
MEDIUM/HEAVY TRUCKS 3 AXLES                           1469
MOPED OR MOTORIZED BICYCLE                             144
MOTORCYCLE - 2 WHEELED                                1103
OTHER                                                  298
OTHER BUS                                              418
OTHER LIGHT TRUCKS (10,000LBS (4,536KG) OR LESS)      1909
OTHER TRUCKS                                           538
PASSENGER CAR                                       147247
PICKUP TRUCK                                          8926
POLICE VEHICLE/EMERGENCY                              1497
POLICE VEHICLE/NON EMERGENCY                          2119
RECREATIONAL VEHICLE                                   198
SINGLE-UNIT TRUCK (BOX)                                338
SPORT UTILITY VEHICLE (SUV)                          22683
TRUCK TRACTOR                                          645
VAN - CARGO/LIGHT TRUCK 2 AXLES                       2100
VAN - PASSENGER                                       5924
NaN                                                   6428
Name: count, dtype: int64

Total number of groups:
27

####Veh_Body_Type Notes, Explanations
"PASSENGER CAR" includes:
- Sedan, hatchback
- STATION WAGON (949)


"OTHER" includes:
- MOTORCYCLE - 3 WHEELED (3)
- LIMOUSINE (16)
- LOW SPEED VEHICLE (40)
- GOLF CART (3)
- AUTOCYCLE (50)
- RECREATIONAL OFF-HIGHWAY VEHICLES (ROV) (7)  
- FARM EQUIPMENT (TRACTOR, COMBINE HARVESTER, ETC.) (3)
- FARM VEHICLE (21)
- CONSTRUCTION EQUIPMENT (BACKHOE, BULLDOZER, ETC.) (25)
- SNOWMOBILE (130)

"VAN" assume Passenger (because otherwise specified)

####Note:  
For "CARGO VAN/LIGHT TRUCK 2 AXLES (OVER 10,000LBS (4,536 KG))",  
the weight is likely to be a mistake in the  
Automated Crash Reporting System (ACRS).

###Buses:
Buses are not grouped, because school bus circumstances are very  
different from local transit buses.  
Both are different from long-distance coaches, which are mostly on highways.

####Groupings for later:
Can group emergency vehicles in different ways.  
For now, want to explore the differences.

In [57]:
# Clean First_Harmful_Event: Remove common 'unknown' / 'other' patterns and 'NAN' string
# Convert to uppercase for consistency
crash_culled_df["First_Harmful_Event"] = crash_culled_df["First_Harmful_Event"].astype(str).str.upper()

values_to_replace_fhe = ["UNKNOWN", "OTHER", "NAN", "NA"]
crash_culled_df["First_Harmful_Event"] = crash_culled_df["First_Harmful_Event"].replace(values_to_replace_fhe, np.nan)

print("Unique values after cleaning First_Harmful_Event:")
print(crash_culled_df["First_Harmful_Event"].unique())
print("\nValue counts for First_Harmful_Event:")
print(crash_culled_df["First_Harmful_Event"].value_counts(dropna=False))

Unique values after cleaning First_Harmful_Event:
['MOTOR VEHICLE IN TRANSPORT' 'PEDALCYCLE' 'PEDESTRIAN' 'FENCE'
 'PARKED VEHICLE' 'CURB' 'TREE (STANDING)' 'OTHER POST, POLE, OR SUPPORT'
 'GUARDRAIL FACE' 'UTILITY POLE/LIGHT SUPPORT' 'CONCRETE TRAFFIC BARRIER'
 'TRAFFIC SIGN SUPPORT'
 'OTHER FIXED OBJECT (WALL, BUILDING, TUNNEL, ETC.)'
 'OTHER NON-FIXED OBJECT' 'ANIMAL (LIVE)' 'OTHER NON-MOTORIST'
 'TRAFFIC SIGNAL SUPPORT' 'MAILBOX' 'OTHER TRAFFIC BARRIER' 'DITCH' nan
 'OVERTURN/ROLLOVER' 'FELL JUMPED FROM MOTOR VEHICLE'
 'OTHER NON-COLLISION' 'BRIDGE PIER OR SUPPORT' 'EMBANKMENT'
 'CABLE BARRIER' 'GUARDRAIL END TERMINAL'
 'RAILWAY VEHICLE (TRAIN, ENGINE)' 'CULVERT' 'THROWN OR FALLING OBJECT'
 'BRIDGE RAIL' 'EXPLOSION OR FIRE' 'SPILLED CARGO'
 'STRIKES OBJECT AT REST FROM MOTOR VEHICLE IN TRANSPORT'
 'STRUCK BY FALLING, SHIFTING CARGO OR ANYTHING SET IN MOTION BY MOTOR VEHICLE'
 'CONSTRUCTION EQUIPMENT' 'IMPACT ATTENUATOR/CRASH CUSHION'
 'BRIDGE OVERHEAD STRUCTURE' 'UNITS SEPARATED'
 'CARGO/EQUIPMENT LOSS OR SHIFT' 'JACKKNIFE' 'OTHER VEHICLE' 'OFF ROAD'
 'FIXED OBJECT' 'OTHER OBJECT' 'ANIMAL' 'BICYCLE' 'OVERTURN' 'BACKING'
 'OTHER NON COLLISION' 'OTHER CONVEYANCE' 'RAILWAY TRAIN'
 'OTHER PEDALCYCLE' 'U-TURN' 'DOWNHILL RUNAWAY' 'IMMERSION']

Value counts for First_Harmful_Event:
First_Harmful_Event
OTHER VEHICLE                                                                   139238
MOTOR VEHICLE IN TRANSPORT                                                       33945
PARKED VEHICLE                                                                   13709
FIXED OBJECT                                                                     12260
PEDESTRIAN                                                                        4800
NaN                                                                               1446
OFF ROAD                                                                          1150
ANIMAL                                                                             964
BICYCLE                                                                            942
CURB                                                                               825
OTHER OBJECT                                                                       770
OTHER FIXED OBJECT (WALL, BUILDING, TUNNEL, ETC.)                                  384
TREE (STANDING)                                                                    331
PEDALCYCLE                                                                         314
OTHER POST, POLE, OR SUPPORT                                                       300
UTILITY POLE/LIGHT SUPPORT                                                         268
OVERTURN                                                                           265
OTHER NON-FIXED OBJECT                                                             224
ANIMAL (LIVE)                                                                      205
OTHER NON COLLISION                                                                159
BACKING                                                                            151
GUARDRAIL FACE                                                                     136
OTHER CONVEYANCE                                                                   132
OTHER NON-MOTORIST                                                                 130
DITCH                                                                               96
TRAFFIC SIGN SUPPORT                                                                89
OVERTURN/ROLLOVER                                                                   87
EMBANKMENT                                                                          86
MAILBOX                                                                             84
OTHER NON-COLLISION                                                                 73
FENCE                                                                               72
CONCRETE TRAFFIC BARRIER                                                            71
FELL JUMPED FROM MOTOR VEHICLE                                                      69
THROWN OR FALLING OBJECT                                                            69
OTHER PEDALCYCLE                                                                    67
OTHER TRAFFIC BARRIER                                                               56
SPILLED CARGO                                                                       56
GUARDRAIL END TERMINAL                                                              45
TRAFFIC SIGNAL SUPPORT                                                              40
U-TURN                                                                              25
CULVERT                                                                             18
STRIKES OBJECT AT REST FROM MOTOR VEHICLE IN TRANSPORT                              18
UNITS SEPARATED                                                                     14
JACKKNIFE                                                                           12
STRUCK BY FALLING, SHIFTING CARGO OR ANYTHING SET IN MOTION BY MOTOR VEHICLE        12
RAILWAY TRAIN                                                                       12
EXPLOSION OR FIRE                                                                   11
BRIDGE RAIL                                                                         10
CONSTRUCTION EQUIPMENT                                                               7
DOWNHILL RUNAWAY                                                                     6
IMMERSION                                                                            5
IMPACT ATTENUATOR/CRASH CUSHION                                                      3
RAILWAY VEHICLE (TRAIN, ENGINE)                                                      3
BRIDGE OVERHEAD STRUCTURE                                                            3
BRIDGE PIER OR SUPPORT                                                               2
CARGO/EQUIPMENT LOSS OR SHIFT                                                        2
CABLE BARRIER                                                                        2
Name: count, dtype: int64

Don't use First_Harmful_Event or Junction, for now.   
Group more, later.

In [59]:
# crash_grouped_df["Veh_Body_Type"] = crash_grouped_df["Veh_Body_Type"].replace({
#     "NAN" : np.nan,
#     "CROSS COUNTRY BUS" : "BUS - CROSS COUNTRY (Coach)",
#     "ALL TERRAIN VEHICLE (ATV)" :  "ALL TERRAIN VEHICLE (ATV/ATC)",
#     "ALL-TERRAIN VEHICLE/ALL-TERRAIN CYCLE (ATV/ATC)" :  "ALL TERRAIN VEHICLE (ATV/ATC)",
#     "TRANSIT BUS" : "BUS - TRANSIT",
#     "MOPED" : "MOPED OR MOTORIZED BICYCLE",
#     "SCHOOL BUS" : "BUS - SCHOOL"
# })

-----------
Optional save df cleaned thus far to csv for backup

In [73]:
#  save df to csv to back up

crash_culled_df.to_csv("crash_data_grouped_1.csv", index=False)

# index = False prevents "Unnamed: 0" column from being added each time file loads.

In [74]:
crash_more_grouping_df = pd.read_csv(
    "https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/main/final/crash_data_grouped_1.csv")


    #usecols = lambda x: x not in ["Second_Harmful_Event", "Driverless_Vehicle", "Veh_Going_Dir", "Route_Type",])

###Above is saved as "crash_data_grouped_1.csv"
--------------
Collision_Type, First_Harmful_Event, and Junction remain,  
although probably won't use for current analysis.

###Working Here, Below

In [75]:
crash_more_grouping_df.head()

,Vehicle_Num,Agency_Name,ACRS_Report_Type,Crash_Date_Time,Related_Non_Motorist,Collision_Type,Weather,Surface_Condition,Ambient_Light,Traffic_Control,...,Parked_Vehicle,Vehicle_Year,Hit_Run,Lane_Type,At_Fault,First_Harmful_Event,Junction,Intersection_Type,Road_Alignment,Road_Condition
0,0,Montgomery County Police,Injury Crash,5/5/26 22:43,NaN,Front to Front,Clear,Dry,Dark - Lighted,No Controls,...,No,2018.0,No,Lane 2,DRIVER,MOTOR VEHICLE IN TRANSPORT,NaN,NaN,Straight,No Defects
1,1,Montgomery County Police,Injury Crash,5/5/26 22:43,NaN,Front to Front,Clear,Dry,Dark - Lighted,No Controls,...,No,2026.0,No,Lane 2,DRIVER,MOTOR VEHICLE IN TRANSPORT,NaN,NaN,Straight,No Defects
2,2,Rockville Police Dept,Property Damage Crash,5/5/26 21:43,NaN,Front to Rear,Clear,Dry,Dark - Lighted,Flashing Traffic Control Signal,...,No,2023.0,No,Lane 2,NaN,MOTOR VEHICLE IN TRANSPORT,ACCELERATION/DECELERATION LANE,NaN,Straight,No Defects
3,3,Rockville Police Dept,Property Damage Crash,5/5/26 21:43,NaN,Front to Rear,Clear,Dry,Dark - Lighted,Flashing Traffic Control Signal,...,No,2005.0,No,Lane 2,NaN,MOTOR VEHICLE IN TRANSPORT,ACCELERATION/DECELERATION LANE,NaN,Straight,No Defects
4,4,Montgomery County Police,Property Damage Crash,5/5/26 21:30,NaN,Angle,Clear,Dry,Dark - Lighted,Lane Use Control Signal,...,No,2025.0,No,Lane 1,DRIVER,MOTOR VEHICLE IN TRANSPORT,CROSSOVER-RELATED,NaN,Straight,No Defects

In [76]:
crash_more_grouping_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214273 entries, 0 to 214272
Data columns (total 30 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Vehicle_Num                 214273 non-null  int64
 1   Agency_Name                 214273 non-null  object
 2   ACRS_Report_Type            214273 non-null  object
 3   Crash_Date_Time             214273 non-null  object
 4   Related_Non_Motorist        6767 non-null    object
 5   Collision_Type              191162 non-null  object
 6   Weather                     199566 non-null  object
 7   Surface_Condition           189141 non-null  object
 8   Ambient_Light               211494 non-null  object
 9   Traffic_Control             182332 non-null  object
 10  Driver_Substance_Use        170904 non-null  object
 11  Non_Motorist_Substance_Use  5654 non-null    object
 12  Driver_At_Fault             209591 non-null  object
 13  Injury_Severity             211299 non-null  object
 14  Driver_Distraction          168451 non-null  object
 15  Drivers_License_State       197636 non-null  object
 16  Vehicle_Damage              207235 non-null  object
 17  Veh_1st_Impact_Loc          211035 non-null  object
 18  Veh_Body_Type               207845 non-null  object
 19  Speed_Limit                 214273 non-null  int64
 20  Parked_Vehicle              212747 non-null  object
 21  Vehicle_Year                208779 non-null  float64
 22  Hit_Run                     206361 non-null  object
 23  Lane_Type                   51324 non-null   object
 24  At_Fault                    190990 non-null  object
 25  First_Harmful_Event         212827 non-null  object
 26  Junction                    111548 non-null  object
 27  Intersection_Type           101990 non-null  object
 28  Road_Alignment              192613 non-null  object
 29  Road_Condition              183209 non-null  object
dtypes: float64(1), int64(2), object(27)
memory usage: 49.0+ MB

In [62]:
# Remove "Unnamed: 0" column from crash_more_grouping_df

# crash_more_grouping_df = crash_more_grouping_df.drop("Unnamed: 0", axis=1)
# print(crash_more_grouping_df.columns)

#TODO: Find out why "Unnamed: 0" column is added each time file downloads.

Index(['Vehicle_Num', 'Agency_Name', 'ACRS_Report_Type', 'Crash_Date_Time',
       'Related_Non_Motorist', 'Collision_Type', 'Weather',
       'Surface_Condition', 'Ambient_Light', 'Traffic_Control',
       'Driver_Substance_Use', 'Non_Motorist_Substance_Use', 'Driver_At_Fault',
       'Injury_Severity', 'Driver_Distraction', 'Drivers_License_State',
       'Vehicle_Damage', 'Veh_1st_Impact_Loc', 'Veh_Body_Type', 'Speed_Limit',
       'Parked_Vehicle', 'Vehicle_Year', 'Hit_Run', 'Lane_Type', 'At Fault',
       'First_Harmful_Event', 'Junction', 'Intersection_Type',
       'Road Alignment', 'Road_Condition'],
      dtype='object')

In [58]:
# Clean Junction: "Non-Junction" = "NON INTERSECTION" = "UNKNOWN" = nan
# Convert to uppercase for consistency
crash_culled_df["Junction"] = crash_culled_df["Junction"].astype(str).str.upper()

values_to_replace_junction = ["NON-JUNCTION", "NON INTERSECTION", "UNKNOWN", "NAN", "NA"]
crash_culled_df["Junction"] = crash_culled_df["Junction"].replace(values_to_replace_junction, np.nan)

print("Unique values after cleaning Junction:")
print(crash_culled_df["Junction"].unique())
print("\nValue counts for Junction:")
print(crash_culled_df["Junction"].value_counts(dropna=False))

Unique values after cleaning Junction:
[nan 'ACCELERATION/DECELERATION LANE' 'CROSSOVER-RELATED'
 'INTERSECTION OR RELATED' 'ENTRANCE/EXIT RAMP OR RELATED'
 'THROUGH ROADWAY' 'DRIVEWAY ACCESS OR RELATED'
 'OTHER LOCATION NOT LISTED ABOVE WITHIN AN INTERCHANGE AREA (MEDIAN,\nSHOULDER AND ROADSIDE)'
 'SHARED-USE PATH OR TRAIL' 'RAILWAY GRADE CROSSING' 'INTERSECTION'
 'INTERSECTION RELATED' 'OTHER DRIVEWAY' 'INTERCHANGE RELATED'
 'COMMERCIAL DRIVEWAY' 'CROSSOVER RELATED' 'RESIDENTIAL DRIVEWAY' 'ALLEY']

Value counts for Junction:
Junction
NaN                                                                                            102725
INTERSECTION                                                                                    62377
INTERSECTION RELATED                                                                            22185
INTERSECTION OR RELATED                                                                         12673
THROUGH ROADWAY                                                                                  4161
COMMERCIAL DRIVEWAY                                                                              2199
INTERCHANGE RELATED                                                                              1809
ACCELERATION/DECELERATION LANE                                                                   1127
DRIVEWAY ACCESS OR RELATED                                                                       1096
ENTRANCE/EXIT RAMP OR RELATED                                                                     880
RESIDENTIAL DRIVEWAY                                                                              816
CROSSOVER-RELATED                                                                                 772
CROSSOVER RELATED                                                                                 745
OTHER DRIVEWAY                                                                                    489
OTHER LOCATION NOT LISTED ABOVE WITHIN AN INTERCHANGE AREA (MEDIAN,\nSHOULDER AND ROADSIDE)       142
ALLEY                                                                                              44
RAILWAY GRADE CROSSING                                                                             28
SHARED-USE PATH OR TRAIL                                                                            5
Name: count, dtype: int64

In [53]:
# Clean Collision_Type: 'other' = 'unknown' = nan
values_to_replace_ct = ["other", "unknown", "OTHER", "UNKNOWN"]
crash_culled_df["Collision_Type"] = crash_culled_df["Collision_Type"].astype(str).replace(values_to_replace_ct, np.nan, regex=True)

print("Unique values after cleaning Collision_Type:")
print(crash_culled_df["Collision_Type"].unique())
print("\nValue counts for Collision_Type:")
print(crash_culled_df["Collision_Type"].value_counts(dropna=False))

Unique values after cleaning Collision_Type:
['Front to Front' 'Front to Rear' 'Angle' 'Single Vehicle'
 'Sideswipe, Opposite Direction' 'nan' 'Rear To Side' 'Rear To Rear'
 'Sideswipe, Same Direction' 'OPPOSITE DIRECTION SIDESWIPE'
 'HEAD ON LEFT TURN' 'STRAIGHT MOVEMENT ANGLE' 'SAME DIR REAR END'
 'HEAD ON' 'SAME DIRECTION SIDESWIPE' 'SAME DIRECTION RIGHT TURN'
 'SAME DIRECTION LEFT TURN' 'ANGLE MEETS LEFT TURN'
 'SAME DIR BOTH LEFT TURN' 'SAME DIR REND LEFT TURN'
 'ANGLE MEETS RIGHT TURN' 'OPPOSITE DIR BOTH LEFT TURN'
 'ANGLE MEETS LEFT HEAD ON' 'SAME DIR REND RIGHT TURN']

Value counts for Collision_Type:
Collision_Type
SAME DIR REAR END                55759
STRAIGHT MOVEMENT ANGLE          30342
nan                              23111
Single Vehicle                   20818
SAME DIRECTION SIDESWIPE         16227
HEAD ON LEFT TURN                12926
Front to Rear                    12494
Angle                             8897
Sideswipe, Same Direction         6706
SAME DIRECTION RIGHT TURN         3832
HEAD ON                           3786
SAME DIRECTION LEFT TURN          3715
OPPOSITE DIRECTION SIDESWIPE      2883
Front to Front                    2352
ANGLE MEETS LEFT TURN             2033
Rear To Side                      1909
Sideswipe, Opposite Direction     1570
ANGLE MEETS RIGHT TURN            1204
SAME DIR REND LEFT TURN            743
SAME DIR REND RIGHT TURN           720
SAME DIR BOTH LEFT TURN            719
ANGLE MEETS LEFT HEAD ON           700
Rear To Rear                       505
OPPOSITE DIR BOTH LEFT TURN        322
Name: count, dtype: int64

In [55]:
# Clean First_Harmful_Event: Remove common 'unknown' / 'other' patterns
# Display unique values to identify cleaning needs, then apply standard replacements
print("Unique values of First_Harmful_Event before cleaning:")
print(crash_culled_df["First_Harmful_Event"].unique())

values_to_replace_fhe = ["unknown", "other", "UNKNOWN", "OTHER"]
crash_culled_df["First_Harmful_Event"] = crash_culled_df["First_Harmful_Event"].astype(str).replace(values_to_replace_fhe, np.nan, regex=True)

print("Unique values after cleaning First_Harmful_Event:")
print(crash_culled_df["First_Harmful_Event"].unique())
print("\nValue counts for First_Harmful_Event:")
print(crash_culled_df["First_Harmful_Event"].value_counts(dropna=False))

Unique values of First_Harmful_Event before cleaning:
['Motor Vehicle In Transport' 'Pedalcycle' 'Pedestrian' 'Fence'
 'Parked Vehicle' 'Curb' 'Tree (standing)' 'Other Post, Pole, Or Support'
 'Guardrail Face' 'Utility Pole/Light Support' 'Concrete Traffic Barrier'
 'Traffic Sign Support'
 'Other Fixed Object (wall, building, tunnel, etc.)'
 'Other Non-Fixed Object' 'Animal (live)' 'Other Non-Motorist'
 'Traffic Signal Support' 'Mailbox' 'Other Traffic Barrier' 'Ditch' nan
 'Overturn/Rollover' 'Fell Jumped from Motor Vehicle'
 'Other Non-Collision' 'Bridge Pier Or Support' 'Embankment'
 'Cable Barrier' 'Guardrail End Terminal'
 'Railway Vehicle (train, engine)' 'Culvert' 'Thrown Or Falling Object'
 'Bridge Rail' 'Explosion Or Fire' 'Spilled Cargo'
 'Strikes Object at Rest from Motor Vehicle In Transport'
 'Struck by Falling, Shifting Cargo Or Anything Set In Motion by Motor Vehicle'
 'Construction Equipment' 'Impact Attenuator/Crash Cushion'
 'Bridge Overhead Structure' 'Units Separated'
 'Cargo/Equipment Loss Or Shift' 'Jackknife' 'OTHER VEHICLE' 'OFF ROAD'
 'FIXED OBJECT' 'OTHER OBJECT' 'ANIMAL' 'BICYCLE' 'OVERTURN' 'BACKING'
 'OTHER NON COLLISION' 'OTHER CONVEYANCE' 'RAILWAY TRAIN'
 'OTHER PEDALCYCLE' 'U-TURN' 'DOWNHILL RUNAWAY' 'IMMERSION']
Unique values after cleaning First_Harmful_Event:
['Motor Vehicle In Transport' 'Pedalcycle' 'Pedestrian' 'Fence'
 'Parked Vehicle' 'Curb' 'Tree (standing)' 'Other Post, Pole, Or Support'
 'Guardrail Face' 'Utility Pole/Light Support' 'Concrete Traffic Barrier'
 'Traffic Sign Support'
 'Other Fixed Object (wall, building, tunnel, etc.)'
 'Other Non-Fixed Object' 'Animal (live)' 'Other Non-Motorist'
 'Traffic Signal Support' 'Mailbox' 'Other Traffic Barrier' 'Ditch' 'nan'
 'Overturn/Rollover' 'Fell Jumped from Motor Vehicle'
 'Other Non-Collision' 'Bridge Pier Or Support' 'Embankment'
 'Cable Barrier' 'Guardrail End Terminal'
 'Railway Vehicle (train, engine)' 'Culvert' 'Thrown Or Falling Object'
 'Bridge Rail' 'Explosion Or Fire' 'Spilled Cargo'
 'Strikes Object at Rest from Motor Vehicle In Transport'
 'Struck by Falling, Shifting Cargo Or Anything Set In Motion by Motor Vehicle'
 'Construction Equipment' 'Impact Attenuator/Crash Cushion'
 'Bridge Overhead Structure' 'Units Separated'
 'Cargo/Equipment Loss Or Shift' 'Jackknife' nan 'OFF ROAD' 'FIXED OBJECT'
 'ANIMAL' 'BICYCLE' 'OVERTURN' 'BACKING' 'RAILWAY TRAIN' 'U-TURN'
 'DOWNHILL RUNAWAY' 'IMMERSION']

Value counts for First_Harmful_Event:
First_Harmful_Event
NaN                                                                             140366
Motor Vehicle In Transport                                                       33945
Parked Vehicle                                                                   13709
FIXED OBJECT                                                                     12260
Pedestrian                                                                        4800
nan                                                                               1446
OFF ROAD                                                                          1150
ANIMAL                                                                             964
BICYCLE                                                                            942
Curb                                                                               825
Other Fixed Object (wall, building, tunnel, etc.)                                  384
Tree (standing)                                                                    331
Pedalcycle                                                                         314
Other Post, Pole, Or Support                                                       300
Utility Pole/Light Support                                                         268
OVERTURN                                                                           265
Other Non-Fixed Object                                                             224
Animal (live)                                                                      205
BACKING                                                                            151
Guardrail Face                                                                     136
Other Non-Motorist                                                                 130
Ditch                                                                               96
Traffic Sign Support                                                                89
Overturn/Rollover                                                                   87
Embankment                                                                          86
Mailbox                                                                             84
Other Non-Collision                                                                 73
Fence                                                                               72
Concrete Traffic Barrier                                                            71
Thrown Or Falling Object                                                            69
Fell Jumped from Motor Vehicle                                                      69
Spilled Cargo                                                                       56
Other Traffic Barrier                                                               56
Guardrail End Terminal                                                              45
Traffic Signal Support                                                              40
U-TURN                                                                              25
Strikes Object at Rest from Motor Vehicle In Transport                              18
Culvert                                                                             18
Units Separated                                                                     14
Jackknife                                                                           12
RAILWAY TRAIN                                                                       12
Struck by Falling, Shifting Cargo Or Anything Set In Motion by Motor Vehicle        12
Explosion Or Fire                                                                   11
Bridge Rail                                                                         10
Construction Equipment                                                               7
DOWNHILL RUNAWAY                                                                     6
IMMERSION                                                                            5
Railway Vehicle (train, engine)                                                      3
Impact Attenuator/Crash Cushion                                                      3
Bridge Overhead Structure                                                            3
Cable Barrier                                                                        2
Bridge Pier Or Support                                                               2
Cargo/Equipment Loss Or Shift                                                        2
Name: count, dtype: int64

In [39]:
import numpy as np

# Rename the column first
crash_culled_df = crash_culled_df.rename(columns={"Road Alignment": "Road_Alignment"})

# Preserve original NaN values
original_nan_mask = crash_culled_df["Road_Alignment"].isna()

# Convert to string and title case for standardization, but only for non-NaN values
# This will turn np.nan into the string 'Nan'
crash_culled_df["Road_Alignment"] = crash_culled_df["Road_Alignment"].astype(str).str.title()

# Standardize 'Straight' values
straight_patterns = ["Straight", "Straight, Straight"]
crash_culled_df["Road_Alignment"] = crash_culled_df["Road_Alignment"].replace(straight_patterns, "Straight")

# Convert all variations of 'Curve' to 'Curved'
curve_patterns = [
    "Curve Left", "Curve Left, Straight", "Curve Right",
    "Curve Left, Curve Right", "Curve Right, Straight", "Curve Left, Curve Right, Straight"
]
crash_culled_df["Road_Alignment"] = crash_culled_df["Road_Alignment"].replace(curve_patterns, "Curved")

# Now, convert the string 'Nan' (which came from original np.nan) back to actual np.nan
crash_culled_df["Road_Alignment"] = crash_culled_df["Road_Alignment"].replace("Nan", np.nan)

# Ensure that any values that were originally NaN are still NaN after all processing
crash_culled_df.loc[original_nan_mask, "Road_Alignment"] = np.nan

print("Unique values after cleaning Road_Alignment:")
print(crash_culled_df["Road_Alignment"].unique())
print("\nValue counts for Road_Alignment:")
print(crash_culled_df["Road_Alignment"].value_counts(dropna=False))

Unique values after cleaning Road_Alignment:
['Straight' 'Curved']

Value counts for Road_Alignment:
Road_Alignment
Straight    173838
Curved       40435
Name: count, dtype: int64

In [48]:
# Clean Vehicle_Damage: caseblind, "unkonwn" = "other" = nan
values_to_replace_vd = ["unkonwn", "other", "UNKNOWN", "OTHER"]
crash_culled_df["Vehicle_Damage"] = crash_culled_df["Vehicle_Damage"].astype(str).replace(values_to_replace_vd, np.nan, regex=True)

print("Unique values after cleaning Vehicle_Damage:")
print(crash_culled_df["Vehicle_Damage"].unique())
print("\nValue counts for Vehicle_Damage:")
print(crash_culled_df["Vehicle_Damage"].value_counts(dropna=False))

Unique values after cleaning Vehicle_Damage:
['DISABLING' 'FUNCTIONAL' 'VEHICLE NOT AT SCENE' 'SUPERFICIAL' 'NO DAMAGE'
 'NAN' 'DESTROYED']

Value counts for Vehicle_Damage:
Vehicle_Damage
DISABLING               79964
SUPERFICIAL             55186
FUNCTIONAL              54644
DESTROYED                7610
NAN                      7038
NO DAMAGE                6691
VEHICLE NOT AT SCENE     3140
Name: count, dtype: int64

In [49]:
# Clean Veh_1st_Impact_Loc: "ROOF TOP" = "roof" = "top"; caseblind; OCLOCK = O Clock to O"Clock

# Convert to uppercase for case-insensitivity to standardize initial replacements
crash_culled_df["Veh_1st_Impact_Loc"] = crash_culled_df["Veh_1st_Impact_Loc"].astype(str).str.upper()

# Standardize "ROOF TOP", "ROOF", "TOP" to "ROOF TOP"
crash_culled_df["Veh_1st_Impact_Loc"] = crash_culled_df["Veh_1st_Impact_Loc"].replace(
    ["ROOF TOP", "ROOF", "TOP"], "ROOF TOP"
)

# Standardize OCLOCK, O CLOCK to O"CLOCK
crash_culled_df["Veh_1st_Impact_Loc"] = crash_culled_df["Veh_1st_Impact_Loc"].replace(
    ["OCLOCK", "O CLOCK"], "O\"CLOCK"
)

print("Unique values after cleaning Veh_1st_Impact_Loc:")
print(crash_culled_df["Veh_1st_Impact_Loc"].unique())
print("\nValue counts for Veh_1st_Impact_Loc:")
print(crash_culled_df["Veh_1st_Impact_Loc"].value_counts(dropna=False))

Unique values after cleaning Veh_1st_Impact_Loc:
['ONE O CLOCK' 'SIX O CLOCK' 'TWELVE O CLOCK' 'TWO O CLOCK'
 'VEHICLE NOT AT SCENE' 'ELEVEN O CLOCK' 'NINE O CLOCK' 'EIGHT O CLOCK'
 'SEVEN O CLOCK' 'FIVE O CLOCK' 'NON-COLLISION' 'TEN O CLOCK'
 'THREE O CLOCK' 'FOUR O CLOCK' 'UNDERSIDE' 'ROOF TOP' 'CARGO LOSS'
 'EIGHT OCLOCK' 'SEVEN OCLOCK' 'TWELVE OCLOCK' 'NAN' 'ONE OCLOCK'
 'SIX OCLOCK' 'TEN OCLOCK' 'FOUR OCLOCK' 'TWO OCLOCK' 'ELEVEN OCLOCK'
 'THREE OCLOCK' 'NINE OCLOCK' 'FIVE OCLOCK']

Value counts for Veh_1st_Impact_Loc:
Veh_1st_Impact_Loc
TWELVE OCLOCK           68025
SIX OCLOCK              34275
ONE OCLOCK              16197
ELEVEN OCLOCK           13774
TWELVE O CLOCK          12274
TWO OCLOCK               6238
TEN OCLOCK               6191
SIX O CLOCK              5818
ONE O CLOCK              4528
ELEVEN O CLOCK           4368
SEVEN OCLOCK             4279
FOUR OCLOCK              4126
FIVE OCLOCK              4064
EIGHT OCLOCK             3700
THREE OCLOCK             3379
NINE OCLOCK              3358
NAN                      3238
VEHICLE NOT AT SCENE     3140
TEN O CLOCK              1794
TWO O CLOCK              1643
SEVEN O CLOCK            1523
THREE O CLOCK            1376
NINE O CLOCK             1344
FIVE O CLOCK             1327
FOUR O CLOCK             1094
EIGHT O CLOCK            1008
NON-COLLISION             841
UNDERSIDE                 711
ROOF TOP                  599
CARGO LOSS                 41
Name: count, dtype: int64

In [47]:
# Clean Vehicle_Damage: caseblind, "unkonwn" = "other" = nan
values_to_replace_vd = ["unkonwn", "other"]
crash_culled_df["Vehicle_Damage"] = crash_culled_df["Vehicle_Damage"].astype(str).replace(values_to_replace_vd, np.nan, regex=True)
# Convert to uppercase for case-insensitivity, then replace
crash_culled_df["Vehicle_Damage"] = crash_culled_df["Vehicle_Damage"].astype(str).str.upper().replace(["UNKNOWN", "OTHER"], np.nan)

print("Unique values after cleaning Vehicle_Damage:")
print(crash_culled_df["Vehicle_Damage"].unique())
print("\nValue counts for Vehicle_Damage:")
print(crash_culled_df["Vehicle_Damage"].value_counts(dropna=False))

Unique values after cleaning Vehicle_Damage:
['DISABLING' 'FUNCTIONAL' 'VEHICLE NOT AT SCENE' 'SUPERFICIAL' 'NO DAMAGE'
 'NAN' 'DESTROYED']

Value counts for Vehicle_Damage:
Vehicle_Damage
DISABLING               79964
SUPERFICIAL             55186
FUNCTIONAL              54644
DESTROYED                7610
NAN                      7038
NO DAMAGE                6691
VEHICLE NOT AT SCENE     3140
Name: count, dtype: int64

In [39]:
# Clean Intersection_Type
crash_culled_df["Intersection_Type"] = crash_culled_df["Intersection_Type"].replace(
    ["ROUNDABOUT", "TRAFFIC CIRCLE"], "Roundabout/Traffic Circle"
)

print("Unique values after cleaning Intersection_Type:")
print(crash_culled_df["Intersection_Type"].unique())

Unique values after cleaning Intersection_Type:
[nan 'Perpendicular' 'Angled/Skewed' 'Roundabout/Traffic Circle'
 'FOUR-WAY INTERSECTION' 'T-INTERSECTION' 'FIVE-POINT OR MORE'
 'Y-INTERSECTION']


Drivers_License_State  change
"XX" to nan,
 change "MX-MEX", "MX-MX-ROO", "MX-GRO" to "Mex",
change CA-ON, CA-QC, ON, QC, BC, and any other codes that are canadian provinces to "Can"

To be cleaned up now:  

- "Intersection_Type"  

- Lane_Type to Parking_Lot Y/N/nan  
check against off road

- Vehicle_Damage:  caseblind, "unkonwn" = "other" = nan

Veh_1st_Impact_Loc : "ROOF TOP" = "roof" = "top"; caseblind; OCLOCK = O Clock to O'Clock

- Driver_Distraction:  Unknown = UNKNOWN = "NO DRIVER PRESENT" nan

- "Collision_Type"  "other" = "unknown" = nan

- Veh_Body_Type : caseblind,  unknown = other,

- First_Harmful_Event :   
- Second_Harmful_Event :  

- Junction : "Non-Junction" =  "NON INTERSECTION" = "UNKNOWN"  = nan

- Intersection_Type :   
"Roundabout/Traffic Circle" = "ROUNDABOUT" = "TRAFFIC CIRCLE"

- Road Alignment: if not Straight or nan then change to curved

####Categorical Data:
ACRS_Report_Type : ['Injury Crash' 'Property Damage Crash' 'Fatal Crash']



####Date/Time:
Date_Time

---------------
####Future research:  
It would be useful to interview representatives of the municipalities about how they classify and record specific details about crashes, such as drug and alcohol use.  
I would also like to know why the handbook lists many more fields in covered by the Automated Crash Reporting System (ACRS)

Maryland Department of State Police
https://mdsp.maryland.gov/Pages/Dashboards/CrashDataDashboard.aspx  
Maryland Crash Data 2024-Present
Map  
Uses updated information, but that information is not shared with the public (only the preliminary information, which may be incomplete or contain errors for the reasons listed).

Age of driver

Include data about passengers:  number of passengers, general age
------------

####Note on Data
In trying to understand the meaning of certain fields, I may have found an error in the Incidents data description on  
https://data.montgomerycountymd.gov/Public-Safety/Crash-Reporting-Incidents-Data/bhju-22kf/about_data  
The "Direction" field is described as "Location - Direction from mile point."  
The "Distance" field is described as "Location - Distance from mile point."  

However, the Maryland Automated Crash Reporting System (ACRS) Field Reference Guide published on  
https://www.nhtsa.gov/sites/nhtsa.gov/files/documents/acrsfieldreference.pdf
(2017 Maryland State Police)  
section 2.19 states:  
"Distance
Definition:
The distance from the referenced Intersecting Road to the crash site.
Explanation:
The distance in feet or miles from the Intersecting Road to crash site."

Section 2.21:  
"Distance Direction
Definition:
The compass direction describing the direction going from the primary and intersecting
roads to the crash.
Explanation:
Units are described in compass points, i.e. North, South East and West. If the crash
occurred in the intersection, select the compass point referenced in the Mile Point
Direction box above."
---------------------

####About Data

Crash Reporting - Incidents Data  
Original data:  
122,000 Rows  
37 Columns  
Each row is a "Collision"

https://data.montgomerycountymd.gov/Public-Safety/Crash-Reporting-Incidents-Data/bhju-22kf/about_data  

"This dataset provides general information about each collision and details of all traffic collisions occurring on county and local roadways within Montgomery County, as collected via the Automated Crash Reporting System (ACRS) of the Maryland State Police, and reported by the Montgomery County Police, Gaithersburg Police, Rockville Police, or the Maryland-National Capital Park Police.

Please note that these collision reports are based on preliminary information supplied to the Police Department by the reporting parties. Therefore, the collision data available on this web page may reflect:

-Information not yet verified by further investigation  
-Information that may include verified and unverified collision data  
-Preliminary collision classifications may be changed at a later date based   upon further investigation  
-Information may include mechanical or human error"

"3.38 Going Direction
Definition:
The direction of the motor vehicles travel on the roadway prior to the crash.
Explanation:
This is not necessarily a compass direction, but must be consistent with the "Distance
Direction" from the Log Mile Information for this roadway."


![crash map disclaimer](https://raw.githubusercontent.com/Alissa-Ouspen/data201_alissa/main/final/crash_map_disclaimer.png)

####Sources:

- Learn types of intersections | Complete Guide to 12 Types  
https://www.dmvpermittests.com/blog/different-types-of-intersections

IGNORE

AI usage tracker:

- For all cells in merged_cleaned_df:
if value in cell == "unkonwn" or "UNKNOWN" or "other" or "OTHER" or "Not Applicable" or "NOT APPLICABLE",  
set value to nan  

- Make all caseblind:  
Compare values in each column.  
If a value written in all caps has a matching value that is written in mixed case or lower case,  
then convert all data written in all caps into the matching version that is written in mixed case or lower case.

- Drivers_License_State change "XX" to nan, change "MX-__" to "Mex", change CA-ON, CA-QC, ON, QC, BC, and any other codes that are canadian provinces to "Can".  List all US states and DC.  List all US territories and create Territories group. Create Foreign/Other group for all else except nan.  

- Veh_1st_Impact_Loc
"ROOF TOP", "roof" : "top"   
OCLOCK, O Clock : O'Clock